- pom.xml
- src/main/java/io/camunda/testing/assertions/ProcessInstanceAssertions.java
Added the spotless maven plugin. This plugin enables us to automatically format our code. I've enabled the google Java formatting and the pom formatting from sortPom
Code changes:
Testing:
Documentation:
> Add automatic formatting of pom files

- src/main/java/io/camunda/testing/assertions/BpmnAssertions.java
- src/main/java/io/camunda/testing/assertions/JobAssert.java
- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
Adds assertions for jobs.
closes #3
Code changes:
Testing:
Documentation:
> 3 job assertions

- src/main/java/io/camunda/testing/assertions/ProcessInstanceAssertions.java
- src/main/java/io/camunda/testing/filters/StreamFilter.java
- src/main/java/io/camunda/testing/filters/VariableRecordStreamFilter.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertionsTest.java
This change makes it possible to assert against the variables of a process. 
closes #4 
Code changes:
Testing:
Documentation:
> Add variable assertions

- src/main/java/io/camunda/testing/assertions/BpmnAssert.java
- src/main/java/io/camunda/testing/assertions/DeploymentAssert.java
- src/main/java/io/camunda/testing/assertions/ProcessAssert.java
- src/test/java/io/camunda/testing/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessAssertTest.java
Adds `DeploymentAssert` and `ProcessAssert`
closes #2
Code changes:
Testing:
Documentation:
> 2 deployment assert

- .github/pull_request_template.md
Add Javadoc checkbox to the Definition of Done in the PR template.
Code changes:
Testing:
Documentation:
> Add javadoc checkbox to PR template

- src/main/java/io/camunda/testing/extensions/ZeebeAssertionsExtension.java
- src/test/java/io/camunda/testing/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/testing/assertions/IncidentAssertTest.java
- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
- src/test/java/io/camunda/testing/assertions/MessageAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- Adds logic to extension to temporarily store the created ZeebeClient so that it can be closed properly after the test
- Refactors tests such that ZeebeClient is only injected into classes which do have test methods
closes #58
Code changes:
Testing:
Documentation:
> Close ZeebeClient

- src/main/java/io/camunda/testing/assertions/BpmnAssert.java
- src/main/java/io/camunda/testing/extensions/ZeebeAssertionsExtension.java
- src/main/java/io/camunda/testing/filters/ProcessEventRecordStreamFilter.java
- src/main/java/io/camunda/testing/filters/StreamFilter.java
- src/main/java/io/camunda/testing/utils/InspectionUtility.java
- src/main/java/io/camunda/testing/utils/ProcessEventInspections.java
- src/main/java/io/camunda/testing/utils/RecordStreamManager.java
- src/main/java/io/camunda/testing/utils/RecordStreamSourceStore.java
- src/main/java/io/camunda/testing/utils/model/InspectedProcessInstance.java
- src/test/java/io/camunda/testing/util/Utilities.java
- src/test/java/io/camunda/testing/utils/ProcessEventInspectionsTest.java
- src/test/resources/timer-start-event-daily.bpmn
Timers don't need their own assertions. What we do need is a way to do assertions on a Process Instance once a timer start event has been triggered. This change allows for a route to the Process Instance assertions using the timer id.
I went with the option of using an `InspectionUtility`. There is unfortunately no obvious entry point for timers which could be used in `BpmnAssert`. The only thing we could use is a timer id, but an `assertThat(String)` method is in my opinion too generic. Another option would be choosing a different name for the assertion entry method in `BpmnAssert` so that we could use the timer id. It would result in something like: `assertThatProcessInstanceStartedByTimer(String timerId)` or something like that. This would be confusing in my opinion, as it seems like …
> Timer assertions

- src/test/java/io/camunda/testing/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/testing/assertions/IncidentAssertTest.java
- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
- src/test/java/io/camunda/testing/assertions/MessageAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/testing/util/Utilities.java
- src/test/java/io/camunda/testing/utils/ProcessEventInspectionsTest.java
This makes sure `waitForIdleState()` is the only place where we still do a `Thread.sleep()`. Having this isolated makes it easier to remove it once we've implemented a way to wait for an idle state in the engine.
Code changes:
Testing:
Documentation:
> Make all utilities use waitForIdleState

- .github/workflows/ci-pipeline.yml
- pom.xml
- Add import secrets step in pipeline to get the secrets out of Hashicorp vault
- Snapshots can be published by triggering the GitHub action manually.
- Use the community-action-maven-release GitHub action to deploy a snapshot version to artifactory. This action also makes it possible to release to maven central, for now the maven credentials have been filled with dummy values. Nothing should be pushed to maven central yet. **This will cause the pipeline to fail when you want to deploy a SNAPSHOT**, however the SNAPSHOT will still publish to Artifactory. It might be somewhat confusing, but I figured it would be fine to get an initial SNAPSHOT out there so we could gather feedback.
- Use the community-hub-release-parent pom. This is required for the community release action. To make sure …
> feat: Deploy snapshot version to artifactory

- README.md
- src/main/java/io/camunda/testing/filters/ProcessInstanceRecordStreamFilter.java
- src/main/java/io/camunda/testing/utils/InspectionUtility.java
- src/main/java/io/camunda/testing/utils/ProcessInstanceInspections.java
- src/test/java/io/camunda/testing/util/Utilities.java
- src/test/java/io/camunda/testing/utils/ProcessInstanceInspectionsTest.java
- src/test/resources/call-activity.bpmn
- src/test/resources/start-end.bpmn
When a process instance is started by a Call Activity element, there is no entry point for the assertions. This makes it impossible to test these process instances. With this change I've introduces a `ProcessInstanceInspections` class which will make it possible to find these process instances and assert over them.
closes #46 
Code changes:
Testing:
Documentation:
> Inspect Call Activity

- src/main/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssert.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssertTest.java
Change signature to assert on Objects instead of Strings
Also extend tests to check it against variables of different types
Code changes:
Testing:
Documentation:
> Improve assert on variables - String -> Object

- src/main/java/io/camunda/zeebe/bpmnassert/testengine/EngineFactory.java
- src/main/java/io/camunda/zeebe/bpmnassert/testengine/IdleStateMonitor.java
- src/main/java/io/camunda/zeebe/bpmnassert/testengine/InMemoryEngineImpl.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/MessageAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/inspections/ProcessEventInspectionsTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/inspections/ProcessInstanceInspectionsTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/util/Utilities.java
This commit re-enables `IdleStateMonitor` and fixes it to make it usable.
Learnings:
- we need to be mindful of multi-threading
- the sequence of events is not always intuitive. E.g. when the stream processor is writing the follow-up events, then the listener calls for the new log entries and the skipped entries can come in before the stream processor finished writing all events.
- Because of that, the old mechanism detected an idle state prematurely, i.e. after the first follow-up event was written to the log and immediately skipped by the record stream processor. It didn't wait whether more follow-up events are to come
- Therefore, there is now a timer started when the first idle state is detected.
- The timer delay may depend on the speed of the machine. So maybe we need to tune this …
> Re-enable IdleStateMonitor

- .github/workflows/deploy-artifact.yml
I've had the infra team rename the location of the secrets in Vault from `camunda-cloud-testing` to `zeebe-process-test`. As a result we modify this location in our CI pipeline.
I've also added the maven central secrets and replaced the dummy values.
Code changes:
Testing:
Documentation:
> Enable maven deployments

- src/main/java/io/camunda/zeebe/process/test/testengine/RecordStreamSourceImpl.java
- src/test/java/io/camunda/zeebe/process/test/multithread/MultiThreadTest.java
- src/test/java/io/camunda/zeebe/process/test/util/Utilities.java
I've added a synchronized around the updating of the list of records in the record stream. I've written a test to verify this change solved the issue in #110 
closes #110 
Code changes:
Testing:
Documentation:
> Make RecordStreamSourceImpl threadsafe

- src/main/java/io/camunda/zeebe/process/test/extensions/ZeebeProcessTestExtension.java
- src/test/java/io/camunda/zeebe/process/test/multithread/MultiThreadTest.java
Fixes the thread leaks that occurred in the unit tests.
- In the extension: close the engine and client when injecting the fields raises an exception.
- In the multithread test: Shutdown the executor service upon test completion.
The thread count seems stable around 70-75 threads:
Relates to #122 
Code changes:
Testing:
Documentation:
> Fix thread leaks

- .github/workflows/deploy-artifact.yml
The deploy-artifact workflow did not publish the unit test results. In case of a test failure you'd have to manually go through the logs to see what failed. Adding these steps will publish the results to make it easier to see what went wrong.
Tested manually: https://github.com/camunda-cloud/zeebe-process-test/actions/runs/1687648571
Code changes:
Testing:
Documentation:
> Publish test report upon failure in deploy workflow

- src/main/java/io/camunda/zeebe/process/test/testengine/IdleStateMonitor.java
Tests randomly got stuck when waiting for the engine to be idle. It generally got stuck around the 5000 tests for me locally. With this fix I reached 30.000 tests without getting stuck.
closes #122 
Code changes:
Testing:
Documentation:
> Tests no longer randomly get stuck when waiting for idle state

- src/main/java/io/camunda/zeebe/process/test/assertions/IncidentAssert.java
- src/test/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssertTest.java
I've cherry-picked the line endings fix from the branch `stability-improvements`.
closes #119
Code changes:
Testing:
Documentation:
> Use System's line separator

- .github/workflows/build-test.yml
- .github/workflows/publish-test-results.yml
PRs from forked repositories would always fail because the workflow is unable to publish the unit test results. This is because the `GITHUB_TOKEN` in these workflows have read-only right.
By putting the publishing of these results in a separate workflow we can work around these access rights. This workflow gets triggered upon completion of the first workflow and downloads the artifacts uploaded in the first workflow. This allows it to publish them without problem.
See: https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
closes #148 
Code changes:
Testing:
Documentation:
> Fix workflows for PRs coming from forked repositories

- .github/workflows/build-test.yml
Due to the limited resources of the github runners executing the tests for all 3 scenarios could result into timeouts when sending message with the client. Changing this parallelisation to only run 1 job at a time will increase the workflow time to ~10 minutes, but should resolve the flakiness of the message tests.
In the future it would be nice to make client configuration customizable, so we could increase the request timeout for just the problematic tests, while still being able to run our jobs in parallel.
closes #98 
Code changes:
Testing:
Documentation:
> Modify the workflow to only run 1 job at a time

- src/main/java/io/camunda/zeebe/process/test/testengine/EngineFactory.java
- src/main/java/io/camunda/zeebe/process/test/testengine/GrpcToLogStreamGateway.java
Running tests would sometimes result in an IndexOutOfBoundsException upon writing commands. This is most likely caused by multiple threads using the same writer. The first thread would be writing, while the seconds thread resets the writer.
Related to #158 
Code changes:
Testing:
Documentation:
> Create separate stream writers and don't write synchronously

- .mvn/jvm.config
- CONTRIBUTING.md
The google java format plugin is incompatible with JDK16+. To fix this we need to set these JVM flags. These flags became available after JDK8. This means that with this fix build will fail on JDK8. Therefore, I've updated the contribution guide to specify contributors have to use JDK11+
closes #121
Code changes:
Testing:
Documentation:
> fix: builds with JDK16 and higher

- src/main/java/io/camunda/zeebe/process/test/testengine/GrpcToLogStreamGateway.java
- src/test/java/io/camunda/zeebe/process/test/multithread/WorkerTest.java
Activating jobs did not make use of the single threaded executor. This caused multiple threads to write at the same time, causing conflicts.
With this fix the synchronized is no longer necessary.
closes #158
Code changes:
Testing:
Documentation:
> Use ExecutorService for activating jobs

- README.md
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/BpmnAssert.java
- assertions/src/test/java/io/camunda/zeebe/process/test/assertions/BpmnAssertTest.java
We already had an entry point for ProcessInstanceEvents, but we missed the ProcessInstanceResults. This change adds this entry point for allowing easy assertions when users have a ProcessInstanceResult.
closes #167 
Code changes:
Testing:
Documentation:
> Add assertion entry point for ProcessInstanceResult

- .github/workflows/deploy-artifact.yml
- engine-agent/Dockerfile
- engine-agent/pom.xml
- engine-agent/src/main/java/io/camunda/zeebe/process/test/engine/agent/ZeebeProcessTestEngine.java
- engine/Dockerfile
- engine/pom.xml
- pom.xml
A new "engine-agent" module has been created. This module will be responsible for containerizing the engine and making it executable. This has been split from the "engine" module, because in the near future we will support using the engine with and without testcontainers. For people running without testcontainers we don't want to expose any of the container related stuff.
Code changes:
Testing:
Documentation:
> Move containerized engine to different module

- api/src/main/java/io/camunda/zeebe/process/test/api/InMemoryEngine.java
- api/src/main/java/io/camunda/zeebe/process/test/api/RecordStreamSource.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/BpmnAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/DeploymentAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/IncidentAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/JobAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/MessageAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- assertions/src/test/java/io/camunda/zeebe/process/test/assertions/BpmnAssertTest.java
- engine-agent/src/main/java/io/camunda/zeebe/process/test/engine/agent/EngineControlImpl.java
- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryEngineImpl.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/RecordStreamSourceImpl.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/PrintRecordStreamExtension.java
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java
- extension/src/test/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtensionTest.java
- filters/pom.xml
- filters/src/main/java/io/camunda/zeebe/process/test/filters/RecordStream.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/StreamFilter.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/multithread/MultiThreadTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
The `RecordStreamSource` interface defines a lot of methods that generic and should be reusable. This PR creates a new `RecordStream` class in the `filters` module. This class will implement these generic functions, so not all `RecordStreamSource` classes have to implement them separately, preventing duplication.
It's quite a refactoring so I've done it in a few steps to make it easier to review:
1. Create the `RecordStream` class containing the shared functionality.
2. Remove the shared functionality from the `RecordStreamSource` interface and the implementation.
3. Use the new `RecordStream` class in the `engine` module.
4. Make the filters in the `filters` module use the new `RecordStream` class.
5. Switch the `RecordStreamSource` to the new `RecordStream` in the other modules.
In …
> Isolate shared RecordStreamSource functionality

- .github/workflows/deploy-artifact.yml
Variable substitution did not work properly. This had 2 reasons. First, the `$IMAGE_ID` and `$TAG` were part of the string and got replaced as these strings.
Second, the `$IMAGE_ID` contains a `/`. This is also the character used as a delimiter in sed. The delimiter has now been changed to `:`.
Code changes:
Testing:
Documentation:
> Fix sed commands

- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/DbStringColumnFamilyTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbColumnFamilyTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- extension/src/test/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtensionTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/assertions/DeploymentAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/assertions/ProcessAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/assertions/ProcessInstanceAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/inspections/ProcessEventInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/inspections/ProcessInstanceInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/multithread/MultiThreadTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/multithread/WorkerTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/assertions/DeploymentAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/assertions/ProcessAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/assertions/ProcessInstanceAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/inspections/ProcessEventInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/inspections/ProcessInstanceInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/multithread/MultiThreadTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/multithread/WorkerTest.java
This PR removes the `public` keywords from our test methods.
jUnit5 supports tests methods without a public keyword. By convention we want methods to be scope as small as possible. We should also adhere to this in our test classes.
closes #197 
Code changes:
Testing:
Documentation:
> Remove public from test methods

- api/src/main/java/io/camunda/zeebe/process/test/api/InMemoryEngine.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryEngineImpl.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ContainerizedEngine.java
Run on idle state is a feature that we don't want to support at this time. It's best to keep the public interface as minimal as possible before the release. If it turns out users wish to use a functionality like these we can always re-add it later.
Code changes:
Testing:
Documentation:
> Remove runOnIdleState functionality

- .gitignore
- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/pom.xml
Introduces the `flatten-maven-plugin` in the build process. The projects are flattened according to the `ossrh` rules.
closes #208
Code changes:
Testing:
Documentation:
> Flatten all POMs for deployment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/general_issue.md
- .github/workflows/build-test.yml
- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/externalDependencies.xml
- .idea/google-java-format.xml
- .idea/saveactions_settings.xml
- CONTRIBUTING.md
- README.md
- pom.xml
* add Idea settings to align with code formatting rules
* Add markdown formatting
* Refactor parent pom
* Change CI to apply code formatting and commit changes if necessary
closes #40
Code changes:
Testing:
Documentation:
> 40 code formatting

- assertions/pom.xml
- engine-agent/pom.xml
- engine/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/pom.xml
This PR gets rid of dependencies to any `slf4j` implementation. Instead we make use of the `slf4j-api`. In our tests we still need to provide an implementation which is done by adding `slf4j-simple` as a test scoped dependency. I got rid of `log4j` as `slf4j-simple` is more lightweight.
I've also gone through the other dependencies. As a result of the module split some of these were unused, or wrongly scoped. This PR also solves these issues.
closes #174 
Code changes:
Testing:
Documentation:
> Cleanup compile time dependencies

- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/pom.xml
- adds dependency checker
- fixes dependency errors
closes #227
Code changes:
Testing:
Documentation:
> 227 dependency checker

- .github/workflows/build-test.yml
- engine-agent/pom.xml
- engine-agent/src/main/java/io/camunda/zeebe/process/test/engine/agent/RecordStreamSourceWrapper.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
This test was flaky because we immediately increased the engine time after doing the deployment. This could result in the engine time being increased, before the timer is scheduled.
That means if the timer is expected to be scheduled in 1 day. It would now be scheduled in 1 day + the increase in engine time. This caused the timer to not be triggered at all.
I also encountered a different flaky test which is also fixed by this pr. This is the `MutltiThreadTest`.
This test was only flaky when running it using testcontainers. The problem lies in the `RecordStreamSourceWrapper`. In this class we would get all the records from the engine (`RecordStreamSource`). These records would be mapped to json and put into a list. The problem for this test was that we just override all records everytime …
> Flaky test fixes

- .idea/google-java-format.xml
Saving a file on IntelliJ would result in different formatting than applying spotless. This was because the google java format settings were not enabled.
This commit enables google java format, which should resolve the dicrepancy between IntelliJ and spotless.
Code changes:
Testing:
Documentation:
> fix: enable google java format settings

- README.md
- api/src/main/java/io/camunda/zeebe/process/test/api/ZeebeTestEngine.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTest.java
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTest.java
General improvements to the README
- Fix maven central version badge
- Add testcontainer dependency
- Add incident assertions
- Add waitForBusyState explanation
- Add engine lifecycle
After version 1.4.0 is released and published in the official docs we can replace the content in this README with a link to the relevant documentation. There is no need to maintain this documentation in 2 places.
Related to #176 
Code changes:
Testing:
Documentation:
> README improvements

- qa/src/test/java/io/camunda/zeebe/process/test/qa/regular/multithread/WorkerTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/multithread/WorkerTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
- remove Thread.sleep()
- wait until process instance gets completed
closes #244
Code changes:
Testing:
Documentation:
> chore: refactor worker test

- .github/workflows/deploy-artifact.yml
The repository will be moved from the camunda-cloud organisation to the camunda organisation. The secrets we use have been made available under a different path to reflect this move.
We should use this location before the actual move. After the move the old secrets will be deleted.
More context: https://jira.camunda.com/browse/INFRA-3127
Related to #250 
Code changes:
Testing:
Documentation:
> Use secrets from different location

- .github/workflows/deploy-artifact.yml
The maven action plugin used to only be able to update the version on the default branch of the repository. Recently a change has been made to make the branch configurable. For this reason a step has been introduced to the workflow to decide our git branch.
It works by first figuring out what the major and minor version of the release are (e.g. 1.4 when the release is 1.4.1). If this fails to yield a result we exit the workflow. Otherwise we will add the branch (stable/major.minor) as an output of this step. This will then be used by the community-action-maven-release as the branch for updating the versions.
I've done some manual test to verify the workflow works as expected. I did this by creating a `stable/0.0` branch and creating some test release. I have deleted this branch and the …
> Update versions on stable branch

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbState.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransactionContext.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/DbStringColumnFamilyTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbColumnFamilyTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ContainerizedEngine.java
- pom.xml
The ColumnFamily interface in Zeebe has been modified. Before it only contained a put method. Starting from version 8.0.0-rc1 this has been replaced with update, insert and upsert methods.
The delete method has been replaced with deleteExisting and deleteIfExists.
In our in memory database we implement this interface. When updating to Zeebe 8.0.0-rc1 these changed need to be merged to keep the code from breaking.
In addition to the ColumnFamily changes the zeebe-protocol-jackson changed in the way we need to do the mapping. This minor mapping change has also been fixed in this PR.
closes #262
Code changes:
Testing:
Documentation:
> Bump Zeebe to version 8.0.0-rc1

- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineStateMonitor.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/examples/AbstractPrCreatedTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/embedded/examples/PrCreatedTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/examples/PrCreatedTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
- qa/src/test/resources/automated-tests.bpmn
- qa/src/test/resources/pr-created.bpmn
We currently only have very minimal processes in our tests. I've created a realistic process and created tests for this. This can be used as an example for users, as well as verify that more complex processes are testable without breaking.
During the creation of this test I've found a few things that have been added/fixed:
1. The idle state grace period was too low. We are playing around with this value to keep tests stable. I have slightly increased it so my tests were no longer flaky.
2. I've added an `extractingLatestCalledProcess` method to `ProcessInstanceAssert`. This allows users to conveniently access the assertions of a process that is called by a call activity. With this we also have a new `hasCalledProcess` assertion.
3. Allow sending message with variables in our testing …
> Realistic example test

- .idea/externalDependencies.xml
- pom.xml
Dependabot does not control the version of the google-java-format plugin used by spotless. By adding an explicit maven dependency on the plugin we can make Dependabot control it.
Note that adding this dependency doesn't change anything to the rest of the project. It also doesn't really interfere with this specific plugin, as it would in the worst case, simply add the same classes twice on the classpath. By using a property, we can control that the dependent version is the same as the one loaded inside spotless.
closes #277 
Code changes:
Testing:
Documentation:
> Explicitly depend on google-java-format

- api/pom.xml
- api/revapi.json
- assertions/pom.xml
- assertions/revapi.json
- extension-testcontainer/pom.xml
- extension-testcontainer/revapi.json
- extension/pom.xml
- extension/revapi.json
- pom.xml
The revapi maven plugin allows us to perform API checks during our maven build. It will check the current build against the latest released version available on maven.
This tool ensures our interfaces are backwards compatibility. Since we only guarantee backwards compatibility on some of our modules it has only been added to these modules.
⚠️ We really should not check our compatibility against pre-releases. I cannot make this change part of this as it will break stuff if we do this before the 8.0.0 release. For this I have created a separate issue: #283 
closes #275 
Code changes:
Testing:
Documentation:
> Check binary compatibility

- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseWriter.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGatewayTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractDeploymentAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractIncidentAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractJobAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/examples/AbstractPrCreatedTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/inspections/AbstractProcessEventInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/inspections/AbstractProcessInstanceInspectionsTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/multithread/AbstractMultiThreadTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/multithread/AbstractWorkerTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
> Backport 301 to stable/8.0

- engine-agent/src/main/java/io/camunda/zeebe/process/test/engine/agent/EngineControlImpl.java
- engine-agent/src/main/java/io/camunda/zeebe/process/test/engine/agent/ZeebeProcessTestEngine.java
- engine-protocol/src/main/proto/engine_control.proto
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/EngineContainer.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java
The start of the engine was tied to the start of testcontainer. This resulted in the following lifecycle:
1. BeforeAll - start the testcontainer and the engine
2. BeforeEach - stop the engine, recreate it and start it (reset)
This causes some strange behaviour. Upon test start we are starting the engine and resetting it without using it. With this change the lifecycle becomes somewhat more natural:
1. BeforeAll - start the testcontainer
2. BeforeEach - start the engine
3. AfterEach - stop the engine and recreate it (new reset)
This new lifecycle also matches more closely with the embedded lifecycle where we do:
1. BeforeEach - create and start the engine
2. AfterEach - stop the engine
closes #304 
related to https://github.com/camunda-community-hub/spring-zeebe/issues/189
_Not all items …
> Testcontainer engine lifecycle

- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/ProcessInstanceRecordStreamFilter.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
- qa/abstracts/src/main/resources/looping-servicetask.bpmn
Sequence flows will never have an event with an ELEMENT_COMPLETED intent. Instead they get a single event with a SEQUENCE_FLOW_TAKEN intent. Because of this we would always filter out any sequence flows in the assertion, making it impossible to assert that a specific flow has been passed. By adding the SEQUENCE_FLOW_TAKEN intent we include sequence flows in our lists and allow asserting whether or not they have been passed.
closes #318 
Code changes:
Testing:
Documentation:
> Support sequence flow in hasPassedElement assertions

- pom.xml
Providing test scope could result in issues. For example:
The zeebe-workflow-engine has commons-lang3 as a dependency. Since it is in our dependencyManagement with a test scope, this means zeebe-worklfow-engine will get this dependency test scoped as well. This results in ClassNotFoundExceptions, since zeebe-workflow-engine expects it to be available on the classpath when running the application regularly.
This would work fine with the embedded version, as it runs in a test scope. The testcontainer version however does not work as the engine does not run in test scope in the container.
Note: as part of a different PR these scopes were already removed from the main branch. Since this commit contains more changes I couldn't cherry-pick this. Therefore this is a new commit targeted to the …
> Don't provide test scope in dependencyManagement

- pom.xml
This PR bumps the Zeebe dependency to 8.0.1.
Code changes:
Testing:
Documentation:
> Update Zeebe dependency to 8.0.1

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineStateMonitor.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineStateMonitorTest.java
Use `hasProcessingReachedTheEnd` to detect state
closes #133
Code changes:
Testing:
Documentation:
> refactor(engine): use hasProcessingReachedTheEnd to detect state

- engine-protocol/src/main/proto/proto.lock
- pom.xml
This PR adds a version format to the revapi configuration. This is a regex that will make sure we only check backwards compatibility against patch, minor and major releases.
I've also checked in the `proto.lock` file. This file is used to check the backwards compatibility of our grpc api.
closes #283 
Code changes:
Testing:
Documentation:
> Don't run revapi against pre releases

- pom.xml
Set zeebe version to 8.1.0-alpha1 as part of the zeebe release process
> build: set zeebe version to 8.1.0-alpha1

- assertions/pom.xml
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssert.java
- assertions/src/test/java/io/camunda/zeebe/process/test/assertions/VariablesMapAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
* refactoring to extract the logic to assert against variables into its own class. This way, the logic can later be reused for process, job and message variables
* slight modification of error messages as a result of this refactoring
* changed comparison logic to be lenient regarding field order in JSON objects
* added test for new assert class
closes #350
Code changes:
Testing:
Documentation:
> 350 lenient value comparison

- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryEngine.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ContainerizedEngine.java
- pom.xml
See #375 
This PR can only be merged with the latest 8.1.0-SNAPSHOT as of today which seems to bring other changes that need to be adjusted first. I prep it anyway and ask to merge (or reimplement) this before releasing the next version (please :-)). Thx!
> Disabling environment variable override for ZeebeClient in test 

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
Changes the default port in order to not conflict with a Zeebe instance running on the same port.
(does not address the request to make the port configurable)
relates to #366
Code changes:
Testing:
Documentation:
> fix: use different default port

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
Now uses a free ephemeral port by default
closes #366 
Code changes:
Testing:
Documentation:
> chore: use ephemeral free port

- README.md
Swaps order in which the different options to run integration tests are mentioned.
closes #371 
Code changes:
Testing:
Documentation:
> Swap order in which options are mentioned

- .github/workflows/build-test.yml
- .github/workflows/deploy-artifact.yml
- engine-agent/pom.xml
For local builds (on a developer's workstation) a Docker image is built by Maven on the fly. This image is then used in QA tests with testcontainers. All tests locally will be run with Java 17.
The GitHub workflows should be unperturbed by this change.
Please have a look at the issue for the intended scope of the change.
I think there could be further steps to also use Maven to build the Docker image as part of the GHA workflows, but I wanted to keep the change set small.
Now, effectively Maven will build a local Docker image that is tagged with the project version and GHA for build and test will build a Docker image that is tagged with the SHA value. So the two shouldn't conflict with each other :crossed_fingers: 
I was also wondering whether we should document this …
> Build docker image with Maven

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java
Expands the RecordLogger to also log the start instructions of `PROCESS_INSTANCE_CREATION` records.
Also adds easier testing to the RecordStreamLoggerTest.
closes #411
Code changes:
Testing:
Documentation:
> Log PROCESS_INSTANCE_CREATION records with start instructions

- .github/workflows/deploy-artifact.yml
related to https://camunda.slack.com/archives/C03AEFWGJ9K/p1657524606321389
I adjusted the Vault paths to the new one + switched to the Camunda org, same secrets in your case but more fitting org wise.
tl;dr - Infra is reorganising Vault paths
closes #
Code changes:
Testing:
Documentation:
> chore(gha): adjust vault path for org secrets

- .github/workflows/deploy-artifact.yml
related to a [recent announcement](https://camunda.slack.com/archives/C03AEFWGJ9K/p1657524606321389) of restructuring Vault.
Secrets have already been copied over to: https://vault.int.camunda.com/ui/vault/secrets/secret/list/products/zeebe/ci/
related to [INFRA-3336](https://jira.camunda.com/browse/INFRA-3336)
Code changes:
Testing:
Documentation:
> chore(ci): update GHA secrets to new Vault path

- .github/workflows/deploy-artifact.yml
Backports #439 and #448 to stable/8.0. I assume the old secrets will be deleted before we get rid of this branch, since we still need to support it for 8 months.
Code changes:
Testing:
Documentation:
> [Backport stable/8.0] Update paths to vault secrets in CI

- .github/workflows/snapshot-test.yml
- pom.xml
We've encountered problems during the release multiple times, because Zeebe contained breaking changes for Zeebe Process Test. By building and running our tests we can identify these problems earlier on in the development process and don't have to fix these during the release process.
Logically we have to decide in the workflow what the next Zeebe SNAPSHOT version will be from the current Zeebe version defined in the pom. There is 2 options for the current version:
1. No alpha version: MAJOR.MINOR.PATCH
2. Alpha version: MAJOR.MINOR.PATCH-alphaX
When it is not an alpha version we need to increment the MINOR version by 1 and append `-SNAPSHOT` at the end. When it is an alpha version we need to replace `alphaX` with `SNAPSHOT`.
closes #465
_Not all items need to be done depending on the …
> Daily test against Zeebe SNAPSHOT version

- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandSender.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseWriter.java
* StreamProcessorBuilder accepts list of records
* CommandWriter and InterPartitionSender are moved to different packages
closes #
Code changes:
Testing:
Documentation:
> Update to recent engine changes

- pom.xml
alpha5 is released. Revert zeebe version to SNAPSHOT to allow continued development.
Related  https://github.com/camunda/zeebe-process-test/pull/489#pullrequestreview-1099236970
> build(deps): revert zeebe version to SNAPSHOT

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
This PR adds support for the PI modification command by adding it to the ZPT gateway. Handling the incoming request was already taken care of in #461.
With this PR we now map the Response of the request as well. For modification this is an empty response. It also adds a testcase to verify that modifying a process instance works. This test is not meant as an exhaustive test for the modification logic. What we're interested in is making sure the request is handled properly by the gateway.
closes #466 
Code changes:
Testing:
Documentation:
> Fully support Process Instance Modification

- .github/workflows/snapshot-test.yml
The command to increase the Zeebe minor by 1 and appending -SNAPSHOT was broken. `            NEW_ZEEBE_VERSION=echo $(echo $CURRENT_ZEEBE_VERSION | awk -F. '/[0-9]+\./{$2++;print}' OFS=.)-SNAPSHOT` would result in bash trying to execute the version. This would result in the message that 8.2.0-SNAPSHOT is not a command:
By moving the $() outward and using backticks this problem is resolved. `NEW_ZEEBE_VERSION=$(echo `echo $CURRENT_ZEEBE_VERSION | awk -F. '/[0-9]+\./{$2++;print}' OFS=.`-SNAPSHOT)` will echo the version instead of trying to execute it.
closes #
Code changes:
Testing:
Documentation:
> Fix version decision command

- .github/workflows/build-test.yml
- bors.toml
This adds [bors](https://github.com/bors-ng/bors-ng) support to this repo.
- runs the CI on a push to `staging` (typically what bors does when instructed to merge a pull request)
- adds a special job that bors can await
- configures bors only to fast-forward the target branch to the merge commit if this job succeeds
closes #536
Code changes:
Testing:
Documentation:
> Add Bors to merge pull requests

- pom.xml
The Zeebe version is set to the SNAPSHOT version in order to resolve this issue. If we don't the main branch would expect version 7.17.0 of the dmn-model. The nightly tests against SNAPSHOT would expect version 7.18.0. Whichever version we'd pick, one of those would always be broken. By changing te main branch to Zeebe SNAPSHOT we resolve this issue.
closes #538
Code changes:
Testing:
Documentation:
> Fix dmn model dependency convergence issue

- .github/workflows/build-test.yml
- bors.toml
Backport of #537 to `stable/8.0`.
relates to #536
Backported manually because there was a failure in the backport-action. Although the cherry-pick was without conflicts: `git cherry-pick -x 9810bb45d4d5a677ded129cd9a3d9996c2f7559e 2ff389d9e28ff9d5d44278a18adc297a24981e19 b577b164dc55fe92e7314e13b87f5d9b253cbf82`, I still needed to fix the CI. Specifically one of the jobs has a different name.
> [Backport stable/8.0] Add Bors to merge pull requests

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Add a logger for the Escalation ValueType. The Escalation ValueType was added recently, and there is no corresponding logger in the zeebe-process-test library. This causes the testAllValueTypesAreMapped() test to fail.
closes #551
Code changes:
Testing:
Documentation:
> fix(filters): add escalation valuetype logger

- .github/workflows/snapshot-test.yml
The Zeebe SNAPSHOT tests are supposed to verify that zeebe-process-test is compatibly with the latest changes in Zeebe. It runs daily to make sure nothing has broken. Caching messes this up. If we restore the cache we are no longer testing against the latest changes. We might be testing against an older cache, missing any changes that could break this project.
closes #
Code changes:
Testing:
Documentation:
> Remove caching from the Zeebe SNAPSHOT tests

- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandWriter.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
Following the refactoring in https://github.com/camunda/zeebe/pull/11115, I've updated the usage of the logstream writer API
> fix: adjust logstream writer usage after refactoring

- .github/workflows/build-test.yml
- .github/workflows/deploy-artifact.yml
- .github/workflows/snapshot-test.yml
Changes the version used for actions/setup-java in all workflows to major version `v3`.
This should reduce the amount of effort needed to update this action (i.e. no more dependabot pull requests unless a new major version is released).
It should also avoid problems when actions/setup-java removes a specific patch release tag (as has happened before, see pull request mentioned below).
Using a major version is possible because GH recommends moving the major release tags along with the minor and patch releases of that same version.
Note that this may result in reduced reproducibility. However, since all tags can be moved, the only way to guarantee reproducibility is by pinning specific commit shas. Since we don't necessarily depend on a specific version, we should trust the maintainers of …
> ci: use major version for actions/setup-java

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Add a logger for the SignalSubscription ValueType. The SignalSubscription ValueType was added recently, and there is no corresponding logger in the zeebe-process-test library. This causes the testAllValueTypesAreMapped() test to fail.
closes #598 
Code changes:
Testing:
Documentation:
> fix(filters): add signal subscription value type logger

- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandSender.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandWriter.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
The CommandSender in Zeebe has changes its interface. We need to modify the interface here as well to prevent compilation failures.
closes #598 
Code changes:
Testing:
Documentation:
> Fixed modified interface of CommandSender

- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/ProcessInstanceRecordStreamFilter.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Like `BpmnElementType`, `BpmnEventType` has been introduced to Zeebe SNAPSHOT for process instance record. so that as a consumer of the record stream, you can distinguish the type of event that is processed.
closes #596 
Code changes:
Testing:
Documentation:
> feat(filters): add event type for process instance record

- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/injection/AbstractInheritanceInjectionTest.java
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/injection/InheritanceInjectionTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/injection/InheritanceInjectionTest.java
The extensions should inject the engine, client and recordstream into the fields that are available. Before this only tried to inject them into the annotated class. This does not work when inheritance is used and the fields are defined on the superclass of the annotated class.
This PR changes the extensions so that it will first look on the annotated class. If it cannot find any of the annotations here, it will work it's way up to the superclass and so on until it either found a field it is able to inject, or no fields at all.
closes #604 
Code changes:
Testing:
Documentation:
> Inject ZPT related fields into superclasses

- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryLogStorage.java
This method was newly added to LogStorage to support appends of unserialized application data. But now this lead to a compilation error in ZPT because it contains a class `InMemoryLogStorage` that implements `LogStorage`.
The [implementation of the test class ListLogStorage](https://github.com/camunda/zeebe/blob/4dd1025f3f3ba86b5aec10d380b9db8550ed0967/logstreams/src/test/java/io/camunda/zeebe/logstreams/util/ListLogStorage.java#L77-L79) seemed like a reasonable solution for zeebe-process-test. It simply writes the contents of the writer into a buffer and appends it as usual.
closes #613
Code changes:
Testing:
Documentation:
> fix: implement InMemoryLogStorage.append

- .github/pull_request_template.md
- README.md
- engine-protocol/src/main/proto/engine_control.proto
Removes the references to Camunda Cloud by renaming it to Camunda Platform 8, or by redirecting the camunda organisation on GitHub instead of the Camunda-cloud organisation.
closes #617
Code changes:
Testing:
Documentation:
> Remove references to Camunda Cloud

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/resources/dmn/drg-force-user.dmn
Add support for standalone decision evaluation in the Zeebe process test library.
closes #573 
Code changes:
Testing:
Documentation:
> feat(engine): support standalone decision evaluation

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Adds a logger for the new ResourceDeletion ValueType. This record only contains a resource key.
closes #443
Code changes:
Testing:
Documentation:
> Add ResourceDeletion ValueType to the logger

- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryEngine.java
Because the constructor of this class and all methods has a public visibility we should make the `InMemoryEngine` public as well to use it in other projects
closes #645 
Code changes:
Testing:
Documentation:
> feat: Make `InMemoryEngine` public

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseWriter.java
Return type is not necessary, since return was always true, which is why it has been removed from the API.
Related to changes made here https://github.com/camunda/zeebe/pull/11865/commits/b4e0e059587be3517606833208d85a0eebf80490
Code changes:
Testing:
Documentation:
> Apply recent API changes

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
Some changes were made in Zeebe. The creation of the processors now requires an InterPartitionCommandSender directly, instead of a deploymentDistributionBehavior.
Besides this it also requires an EngineConfiguration.
closes #
Code changes:
Testing:
Documentation:
> fix(engine): fix compile issues in Engine creation

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseWriter.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamilyIterationContext.java
- pom.xml
Bump zeebe version to latest patch 8.1.9
> deps: bump zeebe version to 8.1.9

- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
This test was previously disabled due to a bug. Now that the bug is resolved, we can re-enable it.
This does not need to be backported, because the test was not disabled on the stable branches.
closes #687 
Code changes:
Testing:
Documentation:
> Re-enable disabled test

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
* The `createEngineProcessors` method was changed in Zeebe as part of [Move GatewayStreamer ownership to engine#12067](https://github.com/camunda/zeebe/pull/12067). The JobStreamer parameter was added.
closes #708
> Fix Zeebe Snapshot issues

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
This PR bumps Zeebe to version 8.2.0, and resets the project version from 8.2.0-alpha5-SNAPSHOT to 8.2.0-SNAPSHOT.
Code changes:
Testing:
Documentation:
> Bump Zeebe to 8.2.0

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
This PR updates the development version and points Zeebe to 8.3.0-SNAPSHOT. I'm not sure why in the release process this was not done - perhaps I did something wrong? :thinking: 
Code changes:
Testing:
Documentation:
> Prepare next release version

- .github/workflows/build-test.yml
This step is copy-pasted from the Zeebe repository. It will run when the test-summary step has completed. If it did it means the PR can be merged.
Adding this makes it so once the CI has passed it automatically comments `bors merge` on the PR. This triggers bors to merge the PR. This removes the maintenance effort of manually having to merge the dependabot PRs.
closes #
Code changes:
Testing:
Documentation:
> Auto-merge minor/patch version update by dependabot

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Fixes the ZPT snapshot tests by adding 2 fixes:
1. Implements the `whileEqualPrefix` method with a `startAtKey`
2. Adds the `ProcessInstanceBatch` value type to the `RecordLogger`
closes #745
Code changes:
Testing:
Documentation:
> Support ProcessInstanceBatch records

- .github/workflows/deploy-artifact.yml
As `set-output` is deprecated, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and will actually get disabled end of May.
https://camunda.slack.com/archives/C01H4NG9XDY/p1683111124388649?thread_ts=1683032927.278609&cid=C01H4NG9XDY
closes #669
> ci(GHA): Migrate set-output to new GHA environment files

- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
- qa/src/test/resources/alternate-start-end.bpmn
- qa/src/test/resources/multiple-call-activity.bpmn
Extracting a called process takes a processId. This processId was used to verify the process has called a child process with this specific id. However, upon extracting the processId was ignored. As a result there was no guarantee that the extracted process actually matched the passed processId.
backport of #710
> [Backport stable/8.0] Verify processId when extracting called process

- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
- qa/abstracts/src/main/resources/alternate-start-end.bpmn
- qa/abstracts/src/main/resources/multiple-call-activity.bpmn
Extracting a called process takes a processId. This processId was used to verify the process has called a child process with this specific id. However, upon extracting the processId was ignored. As a result there was no guarantee that the extracted process actually matched the passed processId.
backport of #710
> [Backport stable/8.1] Verify processId when extracting called process

- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractProcessInstanceAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
- qa/abstracts/src/main/resources/alternate-start-end.bpmn
- qa/abstracts/src/main/resources/multiple-call-activity.bpmn
Extracting a called process takes a processId. This processId was used to verify the process has called a child process with this specific id. However, upon extracting the processId was ignored. As a result there was no guarantee that the extracted process actually matched the passed processId.
backport of #710
> [Backport stable/8.2] Verify processId when extracting called process

- filters/src/main/java/io/camunda/zeebe/process/test/filters/RecordStream.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Adding MESSAGE_BATCH command to allow expire messages in TTL checker in batches
https://github.com/camunda/zeebe/issues/11953
Code changes:
Testing:
Documentation:
> feat: add MESSAGE_BATCH command

- .github/workflows/build-test.yml
Much like what we do for dependabot PRs we can automatically merge back releases to the stable branches as well. Example PR which doesn't get merged automatically now: https://github.com/camunda/zeebe-process-test/pull/835
closes #837
> Auto-merge releases back to stable branch

- .github/workflows/build-test.yml
> [Backport stable/8.2] automerge camundait and backport PRs

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
Currently, the retryBackOff is just ignored.
With this PR, it should be applied
closes #891 
Code changes:
Testing:
Documentation:
> fix (test-engine): Apply retryBackOff of failJob command

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
To ensure the 8.3.0-SNAPSHOT contains the latest changes, as of now it wasn't updated anymore.
See slack https://camunda.slack.com/archives/C0555930H7F/p1695890722290699?thread_ts=1695883999.551589&cid=C0555930H7F
> Set current development version to 8.3.0-SNAPSHOT

- .github/workflows/deploy-artifact.yml
- pom.xml
We should use the project.version when building it from the main branch. If it's triggered via a release the tag should get the tag from the release version.
closes #
Code changes:
Testing:
Documentation:
> Set docker image tag to `project.version` by default

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
> Backport 876 to stable/8.2

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
> Backport 876 to stable/8.1

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
> Backport 876 stable/8.3

- .github/workflows/build-test.yml
- .github/workflows/deploy-artifact.yml
- .github/workflows/snapshot-test.yml
- README.md
- engine-agent/Dockerfile
- engine-agent/pom.xml
- examples/pom.xml
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTest.java
- pom.xml
- qa/embedded/pom.xml
Zeebe recently upgraded to Java 21 (https://github.com/camunda/zeebe/pull/14697).
To remain compatible with Zeebe this project must be upgraded.
closes #939
Code changes:
Testing:
Documentation:
> Upgrade to java 21

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
I only implemented half of the Signal support 🙈 . This PR adds the remainder and adds a test to verify it's possible to broadcast signals.
closes #964
Code changes:
Testing:
Documentation:
> Properly support Signal broadcasting

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #966 to `stable/8.2`.
relates to #964
> [Backport stable/8.2] Properly support Signal broadcasting

- README.md
The main branch readme currently states that Java 21 is required to run embedded process tests.
This can be confusing, as this information applies to 8.4 (alpha) releases, while the common user will use a stable version (8.3)
This PR adds a note that can be removed later.
closes #
Code changes:
Testing:
Documentation:
> Note about Java version compatibility

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java
- pom.xml
Support the new `USER_TASK` value type introduced in Zeebe with https://github.com/camunda/zeebe/issues/14996.
Also supports the new `PROCESS_INSTANCE_MIGRATION` value type introduced in Zeebe with https://github.com/camunda/zeebe/issues/15106
closes #977 
Code changes:
Testing:
Documentation:
> Add user task and process instance migration loggers

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
As a part of [Update Job Timeout epic](https://github.com/camunda/zeebe/issues/15020) we have added a new UpdateJobTimeout command to the gRPC protocol. We must define this endpoint in the ZPT engine.
- Implementing the RPC in the `GrpcToLogStreamGateway`
- Adding a response mapper to the `GrpcResponseMapper`
- Adding a test to verify the update of the timeout for the job
closes #965
Code changes:
Testing:
Documentation:
> Support update job timeout command

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGatewayTest.java
This adds support for the new `MigrateProcessInstance` RPC to ZPT, such that users can try migrating process instances from ZPT. This allows testing migrations before doing so in production.
> [!NOTE]
> This does not add assertions for the migration. That is out of scope.
Additionally, this fixes a test case that no longer added value. The test case was intended to ensure that we don't forget supporting RPCs in ZPT, but the implementation of the test did not function correctly anymore. Now it is able to correctly detect unsupported RPCs again, which [highlighted that `streamActivatedJobs` is not supported by ZPT](https://github.com/camunda/zeebe/issues/11231#issuecomment-1874025863).
closes #972
Code changes: …
> Support using process instance migration from the zeebe client

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGatewayTest.java
Backport of #1012 to `release-8.4.0`.
relates to #972
> [Backport release-8.4.0] Support using process instance migration from the zeebe client

- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryJobStreamer.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGatewayTest.java
- pom.xml
This PR adds support for the `StreamActivatedJobs` RPC with `zeebe-process-test`, including basic back pressure implementation.
Code changes:
Testing:
Documentation:
> Add support for StreamActivatedJobs RPC

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/Bytes.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/BytesTest.java
- qa/abstracts/pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
- qa/abstracts/src/main/resources/test_timer_events.bpmn
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/jobs/TimerTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/jobs/TimerTest.java
Fix for [this bug](https://github.com/camunda/zeebe-process-test/issues/975)
The root cause of this bug was in `Bytes` class `compareTo(final Bytes other)` method.
Before we used to compare byte arrays tin the following way:
```
if (ourByte < otherByte) {
return SMALLER;
} else if (ourByte > otherByte) {
return BIGGER;
} // else { // = equals -> continue }
```
This was leading to incorrect date comparison as we were comparing signed bytes and sometimes the date that was supposed to come after some other date had a negative byte (ex. -97). 
For example:
`2023.10.10 15:50:00` date will look as follows when converted to bytes array: `[0, 0, 1, -117, 25...]`
`2023.11.5 15:50:00` date will look as follows when converted to bytes array: `[0, 0, 1, -117, -97...]`
When comparing these 2 dates we …
> Timer events fail with specific values

- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
ZPT test cases that manipulate time should not buffer messages for a shorter period than they want to travel through time because the message expires. 
Most often, the message expiry is not the event that your test wants to travel through time for, but rather you're doing so to wait for a timer event to trigger. However, time travel in ZPT is only deterministic in the sense that it awaits busy and idle state after time manipulation. That includes message expiry.
I've changed all tests to default to publishing messages without a TTL, so they aren't buffered. This means they cannot expire later during time travel. Instead, messages published without a TTL expire immediately when published.
I've also updated the example test case that showcases both message publication and time travel in the …
> Unflake tests with published messages

- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
Backport of #1040 to `stable/8.2`.
relates to #984
> [Backport stable/8.2] Unflake tests with published messages

- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
Backport of #1040 to `stable/8.1`.
relates to #984
> [Backport stable/8.1] Unflake tests with published messages

- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
Backport of #1040 to `stable/8.3`.
relates to #984
> [Backport stable/8.3] Unflake tests with published messages

- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
The exported stream may have a short delay before it sees records. This means that the test should wait for some time between joining on the client command to migrate, and asserting that some record is exported.
This test case should not verify the exported stream, because that's not what these tests check. The test should focus on the usage of the client and the response it sends rather than on the results it produces in the engine. We have other tests that verify correct behavior inside Zeebe.
closes #1045
Code changes:
Testing:
Documentation:
> Unflake test case EngineClientTest.shouldMigrateProcessInstance

- README.md
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Enhanced the `activateJobs` method in the `GrpcToLogStreamGateway` class to support the `fetchVariable` parameter. 
This addition allows clients to specify which variables should be fetched when activating jobs. 
The change also includes a new test to verify that only the specified variables are returned on job activation.
closes #675 
Code changes:
Testing:
Documentation:
> fix: Add `fetchVariable` parameter support in ActivateJobs RPC

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- pom.xml
The EnumValue is an interface that allows an enum to provide a getValue method that provides a number associated to each enum value. Hardcoding these values is less error prone than using the ordinal.
This was added to zeebe to avoid accidental reordering of column family values.
See:
- https://github.com/camunda/zeebe/pull/16106    
This also updates to 8.5.0-SNAPSHOT of Zeebe, which main should point at anyways.
https://github.com/camunda/zeebe-process-test/actions/runs/7720583417/job/21045722630
Code changes:
Testing:
Documentation:
> Fix InMemoryDb on zeebe 8.5.0-SNAPSHOT with changes to column family type

- README.md
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1058 to `stable/8.4`.
relates to #675
> [Backport stable/8.4] fix: Add `fetchVariable` parameter support in ActivateJobs RPC

- README.md
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1058 to `stable/8.1`.
relates to #675
> [Backport stable/8.1] fix: Add fetchVariable parameter support in ActivateJobs RPC

- README.md
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1058 to `stable/8.2`.
relates to #675
> [Backport stable/8.2] fix: Add fetchVariable parameter support in ActivateJobs RPC

- README.md
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1058 to `stable/8.3`.
relates to #675
> [Backport stable/8.3] fix: Add fetchVariable parameter support in ActivateJobs RPC

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/Bytes.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/BytesTest.java
- qa/abstracts/pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
- qa/abstracts/src/main/resources/test_timer_events.bpmn
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/jobs/TimerTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/jobs/TimerTest.java
Backport of #1028 to `stable/8.3`.
relates to #975
> [Backport stable/8.3] Timer events fail with specific values

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/Bytes.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/BytesTest.java
- qa/abstracts/pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
- qa/abstracts/src/main/resources/test_timer_events.bpmn
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/jobs/TimerTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/jobs/TimerTest.java
Backport of https://github.com/camunda/zeebe-process-test/pull/1028 to stable/8.2.
relates to https://github.com/camunda/zeebe-process-test/issues/975
> [Backport stable/8.2] Timer events fail with specific values

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Adjust the handling of the ThrowError gRPC command to set the variables from the command to the job record. As a result, the variables are set as local variables of the error catch event.
closes #1079 
Code changes:
Testing:
Documentation:
> fix: Set variables from ThrowError command

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1080 to `stable/8.4`.
relates to #1079
> [Backport stable/8.4] fix: Set variables from ThrowError command

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1080 to `stable/8.2`.
relates to #1079
> [Backport stable/8.2] fix: Set variables from ThrowError command

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1080 to `stable/8.3`.
relates to #1079
> [Backport stable/8.3] fix: Set variables from ThrowError command

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/Bytes.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/BytesTest.java
- qa/abstracts/pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
- qa/abstracts/src/main/resources/test_timer_events.bpmn
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/jobs/TimerTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/jobs/TimerTest.java
Backport of https://github.com/camunda/zeebe-process-test/pull/1028 to stable/8.1.
relates to https://github.com/camunda/zeebe-process-test/issues/975
> [Backport stable/8.1] Timer events fail with specific values

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
The main cause of https://github.com/camunda/zeebe-process-test/issues/1001 was the bug fixed via 77e162c5f9017df616b683aa2236ba50218698e8 . Within the same transaction you couldn't insert a previously deleted key, this happened as after processing the first processes complete command a new message start event correlation was triggered, failing as the previous active process instance was still in the database as the transaction wasn't commited and deleted keys of the transaction weren't checked.
I also noticed there was a bug in the `get` by key method, not checking the deletedKeys set either and fixed that too with bf9e1eb5c34f2d11387443253ba60dfdf03e11ed .
I verified the fix as well with the test case provided in the original issue, I decided against adding it though as the unit test …
> fix: db transaction inconsistencies when deleting keys

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
Backport of #1139 to `stable/8.2`.
relates to camunda/zeebe-process-test#1001 #1001
> [Backport stable/8.2] fix: db transaction inconsistencies when deleting keys

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
Backport of #1139 to `stable/8.3`.
relates to camunda/zeebe-process-test#1001 #1001
> [Backport stable/8.3] fix: db transaction inconsistencies when deleting keys

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
Backport of #1139 to `stable/8.4`.
relates to camunda/zeebe-process-test#1001 #1001
> [Backport stable/8.4] fix: db transaction inconsistencies when deleting keys

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
Backport of #1139 to `stable/8.1`.
relates to camunda/zeebe-process-test#1001 #1001
> [Backport stable/8.1] fix: db transaction inconsistencies when deleting keys

- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryLogStorage.java
- pom.xml
This PR helps resolve a compile error in ZPT when building against Zeebe 8.6.0-SNAPSHOT.
To do so, it:
- bumps the zeebe version to `8.6.0-SNAPSHOT` (this is automatically adjusted by the release)
- removes the error handling in the InMemoryLogStorage's append method (this is no longer necessary)
closes #1166 
Code changes:
Testing:
Documentation:
> Don't handle log storage append errors

- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandWriter.java
Added context to `CommandWrite` class due to the latest change in zeebe. See https://github.com/camunda/zeebe/pull/18266
> fix: add context to CommandWriter

- api/pom.xml
- assertions/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/testcontainers/pom.xml
Due to Zeebe Java Client refactor/rename we need to update also the dependency here
related https://github.com/camunda/camunda/issues/19482
> build: update java client dependency

- pom.xml
Due to a clash in dependencies ZPT gains 2 versions of httpcore5. I've set it to the latest version.
closes #1201
Code changes:
Testing:
Documentation:
> Fix httpcore5 dependency convergence issue

- .github/workflows/build-test.yml
Fixes the CI workflow, specifically enabling it for merge queues (fixing the triggers to run) and also updating the auto merge job to use the GitHub CLI to just add to the merge queue.
related to camunda/team-infrastructure#633
Code changes:
Testing:
Documentation:
> build: fix auto merge with merge queues

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
These ValueTypes were missing causing failing tests on the main branch. I've added a quick summary of the records to the logger to fix this problem.
N/A
Code changes:
Testing:
Documentation:
> Add USER and CLOCK ValueTypes to the RecordStreamLogger

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
Due to changes in Zeebe we need to pass the ActorClock along to the StreamProcessor
closes #1225
Code changes:
Testing:
Documentation:
> Provide LogStream with a clock

- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- pom.xml
Provide to stream processor a simple meter registry
> fix: build stream processor with SimpleMeterRegistry

- .github/workflows/build-test.yml
- bors.toml
Related to https://github.com/camunda/team-infrastructure/issues/633 and the removal of Bors instances.
This PR removes the `bors.toml` file, which is no longer used.
> chore: remove bors.toml config file

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Authorizations aren't supported in the next version. The record is bound to change so it's not worth adding a proper logger for this value type right now. It likely isn't worth adding one in the future either, since ZPT is in the process of being deprecated.
N/A
Code changes:
Testing:
Documentation:
> Add empty logger for authorization records

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
Fixed-rate timers don't play nicely with backward time adjustments. For fixed rate timers, an execution is scheduled for ex. 5 seconds in the future. When that execution runs, it schedules the next one, etc. However, when traveling backwards in time, the next scheduled execution never triggers.
The issue needs to be fixed properly in Zeebe. A temporary workaround is to adjust the tests with a future date time.
related to #1230
Code changes:
Testing:
Documentation:
> fix: quick fix for a timer bug

- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
The TimerTest is failing due to an issue with the
process scheduling service in the Zeebe eninge.
The test is disabled to unblock the release of
ZPT while we continue working on a permanent fix
for the test.
related to #1230
Code changes:
Testing:
Documentation:
> Temporarily disable timer test

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
This applies the recent changes of https://github.com/camunda/camunda/pull/22870 to ZPT. The Logstream no longer needs the actor scheduler, as it no longer schedules tasks asynchronously.
This change broke compilation of ZPT against the Zeebe SNAPSHOT version.
NA
Failed a compilation run [here](https://github.com/camunda/zeebe-process-test/actions/runs/11137105744/job/30950000020).
Code changes:
Testing:
Documentation:
> Remove all references of actor scheduler from logstream

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
closes #
Code changes:
Testing:
Documentation:
> fix: add ROLE and TENANT support

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Fixes a compilation error introduces by https://github.com/camunda/camunda/pull/23192: https://github.com/camunda/zeebe-process-test/actions/runs/11320306143/job/31477650086
> fix: add logger for scale records

- pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/injection/AbstractInheritanceInjectionTest.java
The io.camunda:zeebe-client-java was already using 1.68.0 while ZPT used 1.65.1 which caused the client to fail. As ZPT itself depends on GRPC we need to keep both versions generally in sync.
Kudos to @saig0 for root-causing this!
closes #1257
Code changes:
Testing:
Documentation:
> fix: update grpc version to 1.68.0 to fix incompatiblity

- pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/injection/AbstractInheritanceInjectionTest.java
Backport of #1258 to `stable/8.6`.
relates to #1257
> [Backport stable/8.6] fix: update grpc version to 1.68.0 to fix incompatiblity

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Adds the REDISTRIBUTION value type to the record logger introduced with https://github.com/camunda/camunda/pull/24260.
related to https://github.com/camunda/camunda/issues/24013
Code changes:
Testing:
Documentation:
> feat: add REDISTRIBUTION value type to logger

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Adds the ability to the RecordStreamLogger to log records of value type IDENTITY_SETUP using the toString method. This is better than not logging anything, but means the output is json formatted.
This fixes a failing test case.
closes #1269
> Log identity setup record using toString

- README.md
Update the note about the Spring integration in the README.
Update the announcement about Camunda Process Test.
> docs: Update Spring note in README

- pom.xml
Allows to fetch zeebe release artifacts from camunda nexus, if not yet available in maven central.
Will reduce likelihood of a race condition between maven central and the zpt release, as maven can fetch releases from the camunda managed zeebe release repo.
While touching them, reused the already present properties for the repository urls and ids.
> ci: add zeebe-io release repo

- pom.xml
Backport of #1286 to `stable/8.4`.
relates to
> [Backport stable/8.4] ci: add zeebe-io release repo

- pom.xml
Backport of #1286 to `stable/8.5`.
relates to
> [Backport stable/8.5] ci: add zeebe-io release repo

- pom.xml
Backport of #1286 to `stable/8.6`.
relates to
> [Backport stable/8.6] ci: add zeebe-io release repo

- assertions/ignored-changes.json
Otherwise checks failed again for 8.7 alpha version or upcoming patches.
See failed release job https://github.com/camunda/zeebe-process-test/actions/runs/12559751194/job/35016127917
> ci: revapi ignored changes for all 8.7 minor versions

- assertions/ignored-changes.json
Backport of #1295 to `main`.
relates to
> [Backport main] ci: revapi ignored changes for all 8.7 minor versions

- pom.xml
Downgrades `camunda-xml-model` to 7.19.0, as 7.22.0 targets JDK 11, and we depend on it for the `assertions` module, which targets JDK 8.
related to https://github.com/camunda/camunda/issues/26459
> deps: downgrade model due to JDK requirements

- pom.xml
The change of the id caused issues on artifact deploy, as it needs to match the id of the repo from the maven settings to use the correct credentials.
It previously broke because of https://github.com/camunda/zeebe-process-test/pull/1286
> ci: revert nexus.snapshot.repository.id change

- pom.xml
Backport of #1306 to `stable/8.4`.
relates to
> [Backport stable/8.4] ci: revert nexus.snapshot.repository.id change

- pom.xml
Backport of #1306 to `stable/8.5`.
relates to
> [Backport stable/8.5] ci: revert nexus.snapshot.repository.id change

- pom.xml
Backport of #1306 to `stable/8.6`.
relates to
> [Backport stable/8.6] ci: revert nexus.snapshot.repository.id change

- .github/workflows/build-test.yml
We specify the release version to be Java 8 when running the tests, which ensures that we will catch issues where use APIs > JDK 8, or syntax that is unsupported on JDK 8, while still allowing us to use a build environment (including plugins) for greater versions.
The one downside is we won't detect anymore if we pull in transitive dependencies > JDK 8, but this should be detected separately.
> build: run TC tests with Java 21

- extension-testcontainer/pom.xml
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java
Backport of #1280 to `stable/8.6`.
relates to 
original author: @zambrovski
> Backport 1280 to stable/8.6

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
Backport of https://github.com/camunda/zeebe-process-test/pull/1010 as the v3 action is not supported anymore, see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [Backport stable/8.4] build(deps): Bump actions/upload-artifact from 3 to 4

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
Backport of https://github.com/camunda/zeebe-process-test/pull/1010 as the v3 action is not supported anymore, see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [Backport stable/8.3] build(deps): Bump actions/upload-artifact from 3 to 4

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
Backport of #1452 to `release-8.3.20`.
relates to
> [Backport release-8.3.20] [Backport stable/8.3] build(deps): Bump actions/upload-artifact from 3 to 4

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
Backport of #1450 to `release-8.4.16`.
relates to
> [Backport release-8.4.16] [Backport stable/8.4] build(deps): Bump actions/upload-artifact from 3 to 4

- pom.xml
Quick fix for potential issues caused by the version misalignment. It's a bit unfortunate this needs manual alignment, on the other hand it's not the only dep that needs to stay aligned and this one is rather infrequent to change.
closes #1493 
Code changes:
Testing:
Documentation:
> deps: align camunda model version to 7.22 with camunda/camunda

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
Module versions got messed up by renovate.
See e.g. https://github.com/camunda/zeebe-process-test/commit/805ddacc8b76a9ff199b810fa98b2b8e051d1b20 , we need to exclude the repo modules in renovate in a follow-up.
> deps: use root pom version for module dependencies

- pom.xml
- spring-test/pom.xml
This fixes the currently broken stable/8.7 CI, by:
- Backport of #1421.
- Alignment of spring boot version with [camunda/camunda stable/8.7](https://github.com/camunda/camunda/blob/stable/8.7/parent/pom.xml#L103). 
- Removal of explicit management of httpcore, to be inherited from the camunda/camunda deps instead.  (Otherwise test runtime issues occurred)
- Removal of explicit spring-core dependency, to use version managed by spring-boot bom. (Otherwise test runtime issues occurred)
> Fix stable/8.7 CI

- assertions/pom.xml
- qa/testcontainers/pom.xml
Backport of #1496
closes #https://github.com/camunda/zeebe-process-test/issues/1493
> [backport stable/8.6] deps: use bpmn model 7.19 on relevant jdk8 modules

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- pom.xml
- spring-test/common/pom.xml
Meter registry is required, we can provide a new `SimpleMeterRegistry` that is appropriate for testing.
> fix: set required meter registry

- pom.xml
Bump the Jackson version to 2.18.3. This version is also used in Zeebe `8.4` and `8.5` and is required as Zeebe uses
methods that were added with this version.
closes #1542
Code changes:
Testing:
Documentation:
> deps: bump jackson version to 2.18.3

- pom.xml
* Bump the Jackson version to 2.18.3. This version is also used in Zeebe and is required as Zeebe uses
methods that were added with this version.
* Align the httpcore5 version used in ZPT with the version used in Zeebe 8.5 (httpcore5:5.3.3).
* 
⚠️ Merging is blocked until it is determined if we need to downgrade to `httpcore5:5.3.2` and re-release a `8.5` patch.
closes #1542
closes #1545
Code changes:
Testing:
Documentation:
> deps: bump dependencies for 8.5

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
The build was broken, and some tests were failing:
- New record values are implemented by record stream loggers
- protobuf version is updated to align with zeebe protocol
- `InMemoryDb` now implements the new `getMeterRegistry()` method of `ZeebeDb` using `SimpleMeterRegistry`
NA
> Fix the build

- .github/workflows/snapshot-test.yml
This action was bumped to 2.0 without changing the usage in the workflow.
> ci: fix slack notification on failing snapshot test

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java
Every time a record value is added, the RecordStreamLoggerTest fails because we need to implement a nice record logger for that record value.
However, every time we just implement it with toString, which internally uses toJson to fix the failing test.
Instead, of failing every time, we can just accept that new records are logged as json.
> Log all unknown records using toString

- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/NoResultsSearchClientsProxy.java
- pom.xml
The EngineProcessors.createEngineProcessors method now requires a new SearchClientsProxy (https://github.com/camunda/camunda/pull/30146). While it's not actually used yet, it may be used in the future, although it won't serve any purpose in ZPT. Therefore, it's reasonable to implement it with a static implementation that always provides 0 results. This should at least allow compilation of ZPT again.
Please note that this implementation cannot easily be maintained. New additions to the SearchClientsProxy interface will demand new implementations in the NoResultsSearchClientsProxy. We should investigate whether we can find a different place for the proxy to be passed to the processors.
https://github.com/camunda/zeebe-process-test/actions/runs/14074650499/job/39415365949
_Not all items need …
> Provide a no results search query proxy

- engine/src/main/java/io/camunda/zeebe/process/test/engine/NoResultsSearchClientsProxy.java
`ProcessDefinitionFlowNodeStatisticsResult` got renamed to `ProcessFlowNodeStatisticsResult` with https://github.com/camunda/camunda/pull/30530, this adapts ZPT to that breaking change.
relates https://github.com/camunda/camunda/issues/30390
> fix: adapt to search client API changes

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
There were two things off.
1. the `Run tests on ubuntu-latest using testcontainers` job of the `Build and test` workflow was not running the `spring-boot-starter-camunda-test-testcontainer` module but only `zeebe-process-test-qa-testcontainers`, thus we missed to detect broken tests in PRs.
2. The nightly `Zeebe SNAPSHOT test` workflow was running the `spring-boot-starter-camunda-test-testcontainer` tests but not the `zeebe-process-test-qa-testcontainers` tests, with 9d55c2a758ac7134dbd1e931578330f92d103093 it now builds and tests all modules
> ci: run spring testcontainers test in tc job

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
Previous setup was just collecting the report from the top level modules, due to the non-recursive glob pattern used.
relates https://github.com/camunda/zeebe-process-test/issues/1619 - for being able to check the logs of the flaky tests
> ci: collect surefire reports from nested modules

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
Fixed compilation error that was caused by `ScopedColumnFamily` interface that was added to zeebe's `ColumnFamily`, but was not implemented here.
> feat: fix compilation error introduce by adding ScopedColumnFamily bound

- pom.xml
It's not used directly and the only transitive path is via `zeebe-protocol-impl`, see
```
[INFO] --- dependency:3.6.1:tree (default-cli) @ zeebe-process-test-engine ---
[INFO] io.camunda:zeebe-process-test-engine:jar:8.6.16-SNAPSHOT
[INFO] \- io.camunda:zeebe-protocol-impl:jar:8.6.15:compile
[INFO]    \- org.msgpack:jackson-dataformat-msgpack:jar:0.9.9:compile
[INFO]       \- org.msgpack:msgpack-core:jar:0.9.9:compile
[INFO]
...
[INFO] --- dependency:3.6.1:tree (default-cli) @ zeebe-process-test-engine-agent ---
[INFO] io.camunda:zeebe-process-test-engine-agent:jar:8.6.16-SNAPSHOT
[INFO] \- io.camunda:zeebe-process-test-engine:jar:8.6.16-SNAPSHOT:compile
[INFO]    \- io.camunda:zeebe-protocol-impl:jar:8.6.15:compile
[INFO]       \- org.msgpack:jackson-dataformat-msgpack:jar:0.9.9:compile …
```
> build: remove version management for msgpack

- pom.xml
- spring-test/pom.xml
Backport of https://github.com/camunda/zeebe-process-test/pull/1499 to align dependency management from 8.6+, in relation to the new spring based modules.
> [backport stable/8.6] alignment of spring dependency management

- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/configuration/ZeebeTestDefaultConfiguration.java
Backport of https://github.com/camunda/zeebe-process-test/pull/1676
> [backport stable/8.6] fix: adapt to removal of default mapper on camunda/camunda

- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/configuration/ZeebeTestDefaultConfiguration.java
Backport of https://github.com/camunda/zeebe-process-test/pull/1679
> [backport stable/8.7] fix: adapt to removal of default mapper on camunda/camunda

- .github/workflows/build-test.yml
- pom.xml
Backport of #1687 to `stable/8.7`.
relates to #1619
> [Backport stable/8.7] ci: do not fail ci on flaky test on macos

- .github/workflows/build-test.yml
- pom.xml
Backport of #1687 to `stable/8.6`.
relates to #1619
> [Backport stable/8.6] ci: do not fail ci on flaky test on macos

- .github/workflows/build-test.yml
- pom.xml
Backport of #1687 to `stable/8.5`.
relates to #1619
> [backport stable/8.5] ci: do not fail ci on flaky test on macos

- .github/workflows/deploy-artifact.yml
- pom.xml
More details [here](https://camunda.slack.com/archives/C06UWQNCU7M/p1750861970193629?thread_ts=1750849826.611969&cid=C06UWQNCU7M)
The idea is to restore the branch for 8.6.20 to the position where:
- The release workflow is fixed (cherry pick https://github.com/camunda/zeebe-process-test/pull/1751 from `stable/8.6` -> this branch was forked off it before the fix was there)
- The old project version is instantiated (8.6.19) to how it was before the 8.6.20 release has been started
- so that https://github.com/camunda/zeebe-process-test/actions/workflows/create-release.yml can be triggered against the `release-8.6.20`, the artifacts will be built and published anew.
- this payload with be used for the trigger:
```json
{
"ref":"main",
"inputs":{
"releaseType":"patch", …
```
> Fix release procedure after failed 8.6.20 publishing

- .github/workflows/deploy-artifact.yml
- pom.xml
Backport of #1751 to `stable/8.4`.
relates to camunda/team-infrastructure#833
> [Backport stable/8.4] ci: Maven central migration backport

- .github/workflows/deploy-artifact.yml
- pom.xml
Backport of #1751 to `stable/8.5`.
relates to camunda/team-infrastructure#833
> [Backport stable/8.5] ci: Maven central migration backport

- .github/workflows/deploy-artifact.yml
- pom.xml
Backport of #1751 to `stable/8.7`.
relates to camunda/team-infrastructure#833
> [Backport stable/8.7] ci: Maven central migration backport

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
Backport of #1758 to `stable/8.6`.
relates to
> [Backport stable/8.6] fix: implement new ColumnFamily method

- .github/workflows/deploy-artifact.yml
Backport of #1790 to `stable/8.5`.
relates to
> [Backport stable/8.5] fix: use the correct release version

- .github/workflows/deploy-artifact.yml
Backport of #1790 to `stable/8.6`.
relates to
> [Backport stable/8.6] fix: use the correct release version

- filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java
If no value type logger can be found we log an empty string by default. This is good enough as new value types won't be 
supported in ZPT anymore.
closes N/A
Code changes:
Testing:
Documentation:
> Remove value type logger test for 8.7
