- .github/pull_request_template.md
* remove link to Zeebe project
* be less descriptive about backport
n/a
> chore: simplify PR template

- src/test/java/io/camunda/testing/util/Utilities.java
We already talked about refactoring the logic we use in the tests. I started doing this for #2 and the realized, I would like to have it in main earlier, and extracted this smaller PR.
The content is a bit narrow and motivated by what I am going to need in #2.
I tried modifying the existing test, but this got messy quite quickly. 
So, since there really is no perfect time, this PR serves as a start for having this class in the code base.
Code changes:
Testing:
Documentation:
> refactor: extract utility logic for tests

- src/main/java/io/camunda/testing/assertions/BpmnAssert.java
- src/main/java/io/camunda/testing/assertions/ProcessInstanceAssert.java
- src/main/java/io/camunda/testing/extensions/ZeebeAssertionsExtension.java
- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- Refactored some names in order to be consistent with order names in the project.
Code changes:
Testing:
Documentation:
> Rename pi assertions

- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
- src/test/java/io/camunda/testing/util/Utilities.java
Change `JobAssertTest ` to use `Utilities` class
Code changes:
Testing:
Documentation:
> Use Utilities in JobAssertTest

- src/main/java/io/camunda/testing/assertions/BpmnAssert.java
- src/main/java/io/camunda/testing/assertions/MessageAssert.java
- src/main/java/io/camunda/testing/assertions/ProcessInstanceAssert.java
- src/main/java/io/camunda/testing/filters/MessageRecordStreamFilter.java
- src/main/java/io/camunda/testing/filters/MessageStartEventSubscriptionStreamFilter.java
- src/main/java/io/camunda/testing/filters/ProcessMessageSubscriptionRecordStreamFilter.java
- src/main/java/io/camunda/testing/filters/StreamFilter.java
- src/test/java/io/camunda/testing/assertions/MessageAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/testing/util/Utilities.java
- src/test/resources/message-start-event.bpmn
- Added Message assertions
- Conntected Message assertions to Process Instance assertions
closes #9 
Code changes:
Testing:
Documentation:
> Add Message assertions

- src/main/java/io/camunda/testing/assertions/BpmnAssert.java
- src/main/java/io/camunda/testing/assertions/IncidentAssert.java
- src/main/java/io/camunda/testing/assertions/JobAssert.java
- src/main/java/io/camunda/testing/assertions/ProcessInstanceAssert.java
- src/main/java/io/camunda/testing/filters/IncidentRecordStreamFiler.java
- src/main/java/io/camunda/testing/filters/IncidentRecordStreamFilter.java
- src/main/java/io/camunda/testing/filters/StreamFilter.java
- src/test/java/io/camunda/testing/assertions/IncidentAssertTest.java
- src/test/java/io/camunda/testing/assertions/JobAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/testing/util/Utilities.java
Adds incident assertions 
closes #11
Code changes:
Testing:
Documentation:
> Incident assertions

- src/test/java/io/camunda/testing/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/testing/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/testing/util/Utilities.java
- (re)moved all client logic from the ProcessInstanceAssertTest
- (re)moved all constants from the ProcessInstanceAssertTest
Code changes:
Testing:
Documentation:
> Use test Utilities in ProcessInstanceAssertTest

- src/main/java/io/camunda/testing/extensions/ZeebeAssertionsExtension.java
- src/test/java/io/camunda/testing/extensions/ZeebeAssertionsExtensionTest.java
- Split code into separate methods
- Add error handling
- Add unit tests
closes #62
Code changes:
Testing:
Documentation:
> Refactor ZeebeAssertionsExtension

- src/main/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssert.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssertTest.java
Adds a merge operation to the stream.
(We might have similar problems elsewhere. I only fixed the place where I ran into the problem)
closes #78
Code changes:
Testing:
Documentation:
> fix: Add merge operation for stream

- src/test/java/io/camunda/zeebe/bpmnassert/assertions/DeploymentAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/IncidentAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/JobAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/MessageAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/ProcessInstanceAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/inspections/ProcessEventInspectionsTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/inspections/ProcessInstanceInspectionsTest.java
Removed the unused fields from the unit tests.
The engine and client are being used in all the tests. Therefore, only the record stream is removed.
Code changes:
Testing:
Documentation:
> Remove unused fields from tests

- src/main/java/io/camunda/zeebe/bpmnassert/testengine/IdleStateMonitor.java
I first wanted to do some refactoring to address your concerns about the confusing snychronization blocks. 
Then I added some JavaDoc, then I renamed some stuff. Then I felt it was different enough to warrant a new PR.
> Improve IdleStateMonitor

- .github/workflows/deploy-artifact.yml
I forgot some important steps in #94 🙈 
I think this still doesn't need the gpg stuff anymore, as I'm fairly sure it isn't being used.
It will be used once we actually deploy stuff to maven, but for now the community action has it filled with `dummy`.
Code changes:
Testing:
Documentation:
> Add checkout and setup java steps

- pom.xml
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/IncidentAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/assertions/JobAssertTest.java
- src/test/java/io/camunda/zeebe/bpmnassert/util/Utilities.java
Add flaky tests plugin to maven, so flaky tests will fail the build.
Code changes:
Testing:
Documentation:
> Add flaky tests plugin

- src/main/java/io/camunda/zeebe/bpmnassert/testengine/InMemoryEngine.java
- src/main/java/io/camunda/zeebe/bpmnassert/testengine/RecordStreamSource.java
Added javadoc to public interfaces. These interfaces are visible to the users, so they should be documented.
Code changes:
Testing:
Documentation:
> Add javadoc to public interfaces

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- README.md
- Added contribution guide. Mostly copied from Zeebe, but edited where necessary.
- Added a bug report template for guidance when submitting a bug report.
closes #16 
Code changes:
Testing:
Documentation:
> Add contribution guide (and bug report template)

- pom.xml
Update Zeebe and Log4J versions
Code changes:
Testing:
Documentation:
> Update Zeebe and Log4J versions

- README.md
- Instead of referencing a snapshot version reference `X.Y.Z` so we don't have to keep this version updated with every release
- Added maven central badge
- Added credits to Camunda BPMN Assert
Code changes:
Testing:
Documentation:
> Update readme with generic version and credit to BPMN assert

- .github/workflows/build-test.yml
- .github/workflows/deploy-artifact.yml
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
Bump zeebe version to `1.4.0-alpha1` as a preparation for the alpha2 release. This allows me to already fix a test that will certainly break otherwise. 
Code changes:
Testing:
Documentation:
> build(deps): bump zeebe to version 1.4.0-alpha1

- api/src/main/java/io/camunda/zeebe/process/test/api/InMemoryEngine.java
- api/src/main/java/io/camunda/zeebe/process/test/api/RecordStreamSource.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/BpmnAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/DeploymentAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/JobAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/MessageAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/ProcessInstanceAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/inspections/InspectionUtility.java
- assertions/src/main/java/io/camunda/zeebe/process/test/inspections/ProcessEventInspections.java
- assertions/src/main/java/io/camunda/zeebe/process/test/inspections/ProcessInstanceInspections.java
- assertions/src/main/java/io/camunda/zeebe/process/test/inspections/model/InspectedProcessInstance.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ContainerizedEngine.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/EngineContainer.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/RecordStreamSourceImpl.java
- extension-testcontainer/src/main/java/io.camunda.zeebe.process.test.extension.testcontainer/ZeebeProcessTestExtension.java
- extension/src/main/java/io/camunda/zeebe/process/test/extension/ZeebeProcessTestExtension.java
- qa/src/test/java/io/camunda/zeebe/process/test/qa/util/Utilities.java
This PR adds / improves javadoc on the classes that will be commonly used by users.
closes #196 
Code changes:
Testing:
Documentation:
> Javadoc improvements

- .github/workflows/build-test.yml
- CONTRIBUTING.md
- pom.xml
The repo has been moved from the camunda-cloud organisation to the camunda organisation. The urls should be updated accordingly.
closes #250
Code changes:
Testing:
Documentation:
> Update organisation in urls

- pom.xml
> chore(pom): remove obsolete property

- pom.xml
See ticket description
Related to INFRA-3107
> chore(maven): change to new Artifactory URL

- pom.xml
This PR bumps Zeebe version to 8.0.2.
Code changes:
Testing:
Documentation:
> Bump Zeebe to 8.0.2

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- pom.xml
closes #
Code changes:
Testing:
Documentation:
> build: bump Zeebe version to 8.1.0-alpha2

- .github/workflows/build-test.yml
Tests these days seem stable enough to be able to run properly in parallel. I've tried 5 successful runs without problems, so let's try this again as it saves ~10 minutes.
Code changes:
Testing:
Documentation:
> Run tests on all operating systems in parallel

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
Adds mapping for start instructions to gateway.
(Applies to both `CreateProcessInstance` as well as `CreateProcessInstanceWithResult` - the second case is calling the mapping code of the first case)
closes #410
Code changes:
Testing:
Documentation:
> feat: add start instructions to gateway mapping

- pom.xml
This PR bumps the Zeebe dependency to 8.0.4.
Code changes:
Testing:
Documentation:
> deps: bump zeebe to 8.0.4

- pom.xml
This PR bumps Zeebe version to 8.0.5.
Code changes:
Testing:
Documentation:
> Bump Zeebe to 8.0.5

- .github/workflows/snapshot-test.yml
Let's not bother the medic (and myself since I get emails ...) during the weekends.
None
Code changes:
Testing:
Documentation:
> Only run snapshot tests on working days

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- pom.xml
Adjust the code base to the recent engine abstraction refactorings
closes #
Code changes:
Testing:
Documentation:
> Apply recent engine refactorings

- pom.xml
Update zeebe version to 8.1.0-alpha5
> build(deps): update zeebe version to 8.1.0-alpha5

- pom.xml
> deps: update zeebe version to 8.0.7

- pom.xml
Updates zeebe dependency to `8.1.2`.
Task https://bru-3.tasklist.ultrawombat.com/b051f158-2779-479f-84dc-1f16c8f808df/2251799818094998
Code changes:
Testing:
Documentation:
> Zeebe release 8.1.2

- pom.xml
Updates zeebe dependency to `8.0.8`.
[Task](https://bru-3.tasklist.ultrawombat.com/3953a05c-7c20-41fb-8231-ec283dd2138b/2251799815301564?filter=all-open)
Code changes:
Testing:
Documentation:
> Zeebe release 8.0.8

- pom.xml
Updates zeebe dependency to `8.1.3`.
[Task](https://bru-3.tasklist.ultrawombat.com/3953a05c-7c20-41fb-8231-ec283dd2138b/4503599628982460?filter=all-open)
Code changes:
Testing:
Documentation:
> Zeebe release 8.1.3

- pom.xml
The old url is taken down. In order to do patch releases on this version we need to set the new url
closes #
Code changes:
Testing:
Documentation:
> fix(ci): use new nexus url

- pom.xml
Bumps zeebe version to `8.2.0-alpha1`
[task](https://bru-3.tasklist.ultrawombat.com/3953a05c-7c20-41fb-8231-ec283dd2138b/2251799815298213?filter=all-open) 
Code changes:
Testing:
Documentation:
> Zeebe release 8.2.0-alpha1

- pom.xml
Bump Zeebe version from 8.1.3 to 8.1.4
closes #
Code changes:
Testing:
Documentation:
> Bump Zeebe version from 8.1.3 to 8.1.4

- engine/src/main/java/io/camunda/zeebe/process/test/engine/CommandWriter.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- pom.xml
feat(deps): change Zeebe version to 8.2.0-alpha2
> feat(deps): change Zeebe version to 8.2.0-alpha2

- pom.xml
Followed - tbh I'm not sure whether this is correct 
Code changes:
Testing:
Documentation:
> Upgrade to alpha3

- pom.xml
Updates the patch version of zeebe.
closes #
Code changes:
Testing:
Documentation:
> Stable 8 0 update zeebe version

- pom.xml
[bump zeebe version to 8.1.6](https://github.com/camunda/zeebe-process-test/pull/627/commits/da6a88b1d8bdb99e1c275d215e924d7473e89a94)
closes #
Code changes:
Testing:
Documentation:
> Bump zeebe version on stable branch

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/resources/dmn/drg-force-user.dmn
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
The current test against Zeebe snapshot fails, because we have no logging for signal event defined. This PR fixes this issue.
Failing build https://github.com/camunda/zeebe-process-test/actions/runs/3784816277/jobs/6434402216
Commit which adds logging https://github.com/camunda/zeebe-process-test/commit/f01b7b62b938c723bb00c5bbf50d0a4d3b1ef824
closes #619 
Code changes:
Testing:
Documentation:
> Add Signal logging

- pom.xml
Bump the dependency on Zeebe to the newly released `8.2.0-alpha4`
/
Code changes:
Testing:
Documentation:
> feat(deps): bump zeebe to 8.2.0-alpha4

- pom.xml
Revert Zeebe to version `8.2.0-SNAPSHOT` after the `8.2.0-alpha4` release.
/
Code changes:
Testing:
Documentation:
> feat(deps): set zeebe version to 8.2.0-SNAPSHOT

- pom.xml
> deps: upgrade zeebe to 8.0.11

- pom.xml
Bump to Zeebe 8.1.7
/
Code changes:
Testing:
Documentation:
> feat(deps): bump zeebe version to 8.1.7

- pom.xml
Update Zeebe version to the latest release 8.1.8
> Update zeebe version to 8.1.8

- pom.xml
Backport #651 to stable/8.0
This version update has fixes to make releases more convenient and less confusing for us.
> Backport 651 to stable/8.0

- pom.xml
Backport #651 to stable/8.1
This version update has fixes to make releases more convenient and less confusing for us.
> Backport 651 to stable/8.1

- pom.xml
> deps: bump zeebe version to 8.0.12

- pom.xml
Fix spring dependency convergence issue which occurred [here](https://github.com/camunda/zeebe-process-test/actions/runs/4498336355/jobs/7914844261)
> Fix dependency convergence issue

- pom.xml
Bump Zeebe to 8.1.10.
Code changes:
Testing:
Documentation:
> deps: bump zeebe to 8.1.10

- pom.xml
Bump Zeebe to 8.0.13
Code changes:
Testing:
Documentation:
> deps: bump zeebe to 8.0.13

- pom.xml
This PR bumps Zeebe to 8.2.1 for the next patch release.
Code changes:
Testing:
Documentation:
> Bump Zeebe to 8.2.1

- pom.xml
> deps: bump zeebe to 8.2.2

- pom.xml
Upgrads Zeebe to 8.2.3
closes #
Code changes:
Testing:
Documentation:
> deps: upgrade zeebe to 8.2.3

- pom.xml
Upgrade zeebe version to 8.1.11
closes #
Code changes:
Testing:
Documentation:
> deps: upgrade zeebe to 8.1.11

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
Merge release branch back to stable branch
Also contains changes from #748
> Release 8.1.12

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Backport of #746 to `stable/8.1`.
relates to #745
> [Backport stable/8.1] Support ProcessInstanceBatch records

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
- pom.xml
Merge release branch back to stable branch
Also contains changes from #747
> Release 8.2.4

- pom.xml
Merge release branch back to main
> Release 8.3.0-alpha1

- pom.xml
> Release 8.1.13

- pom.xml
> Release 8.2.7

- pom.xml
> Release 8.0.17

- pom.xml
> Release 8.2.8

- pom.xml
> Release 8.0.18

- pom.xml
> Release 8.1.14

- pom.xml
> Release 8.2.9

- pom.xml
> Release 8.2.10

- .github/workflows/build-test.yml
> [Backport stable/8.1] automerge camundait and backport PRs

- .github/workflows/build-test.yml
> [Backport stable/8.0] automerge camundait and backport PRs

- pom.xml
> Release 8.2.11

- pom.xml
> Release 8.0.19

- pom.xml
> Release 8.2.12

- pom.xml
> Release 8.2.13

- pom.xml
> Release 8.0.20

- pom.xml
> Release 8.0.21

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
closes #894 
Code changes:
Testing:
Documentation:
> fix: add form as new value type for stream logger

- pom.xml
> Release 8.1.16

- pom.xml
> Release 8.2.14

- README.md
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/DeploymentAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/assertions/FormAssert.java
- assertions/src/main/java/io/camunda/zeebe/process/test/inspections/FormInspectionsUtility.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/resources/form/test-form-1.form
- filters/src/main/java/io/camunda/zeebe/process/test/filters/FormStreamFilter.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/RecordStream.java
- filters/src/main/java/io/camunda/zeebe/process/test/filters/StreamFilter.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractFormAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/inspections/AbstractFormInspectionsTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
- qa/abstracts/src/main/resources/test-form-v2.form
- qa/abstracts/src/main/resources/test-form.form
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/assertions/FormAssertTest.java
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/inspections/FormInspectionsTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/assertions/FormAssertTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/inspections/FormInspectionsTest.java
closes #887 
Code changes:
Testing:
Documentation:
> Support form deployment

- pom.xml
> Release 8.2.15

- pom.xml
> Release 8.2.16

- pom.xml
> Release 8.1.17

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
The count methods were missing after updating to zeebe 8.3.0.
> fix: implement ColumnFamily count methods

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- pom.xml
> Release 8.3.0

- pom.xml
> Release 8.1.19

- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #966 to `stable/8.3`.
relates to #964
> [Backport stable/8.3] Properly support Signal broadcasting

- .github/workflows/backport.yml
Prevent the backport action user from triggering on his own /backport commands
N/A
Code changes:
Testing:
Documentation:
> Prevent backport loops

- pom.xml
Bumps Zeebe to 8.1.20 for stable/8.1
Code changes:
Testing:
Documentation:
> deps: bump zeebe version to 8.1.20

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
Bump the project version to `8.4.0-SNAPSHOT` after the `8.3.0` release.
**_Note_**: This was missed after the last release.
closes #
Code changes:
Testing:
Documentation:
> chore(project): prepare for next release

- pom.xml
> Release 8.3.3

- pom.xml
> Release 8.2.18

- pom.xml
> Release 8.2.19

- pom.xml
> Release 8.1.21

- pom.xml
> Release 8.3.5

- pom.xml
> Release 8.2.20

- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcResponseMapper.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGateway.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/InMemoryJobStreamer.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/GrpcToLogStreamGatewayTest.java
- pom.xml
Backport of #1020 to `stable/8.4`.
relates to
> [Backport stable/8.4] Add support for StreamActivatedJobs RPC

- pom.xml
> Release 8.1.22

- examples/src/test/java/io/camunda/zeebe/process/test/examples/PullRequestProcessTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/assertions/AbstractMessageAssertTest.java
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/util/Utilities.java
Backport of #1040 to `stable/8.4`.
relates to #984
> [Backport stable/8.4] Unflake tests with published messages

- pom.xml
> Release 8.2.21

- engine/src/test/java/io/camunda/zeebe/process/test/engine/EngineClientTest.java
Backport of #1046 to `stable/8.4`.
relates to #1045
> [Backport stable/8.4] Unflake test case EngineClientTest.shouldMigrateProcessInstance

- pom.xml
> Release 8.4.1

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/Bytes.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/BytesTest.java
- qa/abstracts/pom.xml
- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
- qa/abstracts/src/main/resources/test_timer_events.bpmn
- qa/embedded/src/test/java/io/camunda/zeebe/process/test/qa/embedded/jobs/TimerTest.java
- qa/testcontainers/src/test/java/io/camunda/zeebe/process/test/qa/testcontainer/jobs/TimerTest.java
Backport of #1028 to `stable/8.4`.
relates to #975
> [Backport stable/8.4] Timer events fail with specific values

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- pom.xml
> Release 8.1.23

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- pom.xml
> Release 8.2.22

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- pom.xml
> Release 8.4.2

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbFactory.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- pom.xml
> Release 8.3.6

- pom.xml
> Release 8.3.7

- pom.xml
> Release 8.4.3

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
Backport of #923 to `release-8.1.24`.
relates to
> [Backport release-8.1.24] fix: implement ColumnFamily count methods

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
Backport of #923 to `release-8.2.23`.
relates to
> [Backport release-8.2.23] fix: implement ColumnFamily count methods

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
- pom.xml
> Release 8.1.24

- pom.xml
> Release 8.1.25

- pom.xml
> Release 8.4.4

- .github/workflows/build-test.yml
closes #
Code changes:
Testing:
Documentation:
> Increase timeout of workflows

- .github/workflows/build-test.yml
- pom.xml
> Release 8.3.8

- pom.xml
> Release 8.2.24

- pom.xml
> Release 8.1.26

- pom.xml
> Release 8.2.25

- pom.xml
> Release 8.3.9

- pom.xml
> Release 8.4.5

- .github/workflows/build-test.yml
- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbTransaction.java
- engine/src/test/java/io/camunda/zeebe/process/test/engine/db/InMemoryZeebeDbTransactionTest.java
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
> Release 8.5.0

- pom.xml
> Release 8.2.26

- pom.xml
> Release 8.1.27

- pom.xml
> Release 8.3.10

- pom.xml
> Release 8.4.6

- pom.xml
> Release 8.2.27

- pom.xml
> Release 8.5.1

- pom.xml
> Release 8.4.7

- pom.xml
> Release 8.3.11

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
Due to https://github.com/camunda/camunda/issues/20164 where a new Record Value is added
> fix: add message correlation log to record stream

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
Mirrors the changes in Zeebe here: https://github.com/camunda/camunda/pull/20339
> fix: building the logstream is synchronous

- api/pom.xml
- assertions/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/testcontainers/pom.xml
> refactor: remove camunda client

- api/pom.xml
- assertions/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/testcontainers/pom.xml
Backport of #1214 to `release-8.6.0-alpha4`.
relates to
> [Backport release-8.6.0-alpha4] refactor: remove camunda client

- pom.xml
While releasing 8.2.30 we can dependency convergence error:
```
Error:  
Dependency convergence error for org.camunda.bpm.model:camunda-xml-model:jar:7.18.0 paths to dependency are:
+-io.camunda:zeebe-process-test-engine:jar:8.2.30-SNAPSHOT
+-io.camunda:zeebe-workflow-engine:jar:8.2.30:compile
+-io.camunda:zeebe-dmn:jar:8.2.30:compile
+-org.camunda.bpm.model:camunda-dmn-model:jar:7.18.0:compile
+-org.camunda.bpm.model:camunda-xml-model:jar:7.18.0:compile
and
+-io.camunda:zeebe-process-test-engine:jar:8.2.30-SNAPSHOT
+-io.camunda:zeebe-workflow-engine:jar:8.2.30:compile
+-io.camunda:zeebe-bpmn-model:jar:8.2.30:compile
+-org.camunda.bpm.model:camunda-xml-model:jar:7.22.0-alpha3:compile
and
+-io.camunda:zeebe-process-test-engine:jar:8.2.30-SNAPSHOT …
```
> Fix dmn model dependency convergence issue

- pom.xml
> Release 8.3.14

- pom.xml
> Release 8.4.10

- pom.xml
> Release 8.5.6

- qa/abstracts/src/main/java/io/camunda/zeebe/process/test/qa/abstracts/jobs/AbstractTimerTest.java
Backport of #1233 to `main`.
relates to #1230
> [Backport main] Temporarily disable timer test

- pom.xml
> Release 8.3.16

- pom.xml
> Release 8.2.32

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
> Release 8.6.0

- filters/src/main/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLogger.java
closes #
Code changes:
Testing:
Documentation:
> feat: add GROUP and MAPPING value type

- pom.xml
> Release 8.6.3

- pom.xml
> Release 8.6.4

- pom.xml
> Release 8.3.17

- pom.xml
> Release 8.4.13

- pom.xml
> Release 8.5.9

- pom.xml
> Release 8.6.5

- pom.xml
We want to use the newest version of junit5 in our project. 
Including zeebe-process-test-dependency leads to junit5-version-conflicts.
Code changes:
Testing:
Documentation:
> Updating junit5-Version to 5.11.3

- pom.xml
> Release 8.3.18

- pom.xml
> Release 8.4.14

- pom.xml
> Release 8.5.10

- pom.xml
> Release 8.6.6

- pom.xml
Some dependencies were out of sync.
Reference https://github.com/camunda/camunda/blob/stable/8.6/parent/pom.xml#L58
> ci: alignment of dependencies with zeebe 8.6

- pom.xml
Some dependencies were out of sync.
Reference https://github.com/camunda/camunda/blob/stable/8.5/parent/pom.xml#L58
> ci: alignment of dependencies with zeebe 8.5

- pom.xml
Some dependencies were out of sync.
Reference https://github.com/camunda/camunda/blob/stable/8.4/parent/pom.xml#L58
> ci: alignment of dependencies with zeebe 8.4

- pom.xml
Some dependencies were out of sync.
Reference https://github.com/camunda/camunda/blob/stable/8.3/parent/pom.xml#L58
> ci: alignment of dependencies with zeebe 8.3

- pom.xml
> Release 8.4.15

- pom.xml
- spring-test/pom.xml
Otherwise incompatibility exceptions are thrown on runtime.
closes #
Code changes:
Testing:
Documentation:
> ci: bump protobuf to 4.29.3 to align with camunda/camunda

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
- pom.xml
> Release 8.3.20

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
- pom.xml
> Release 8.4.16

- pom.xml
> Release 8.5.13

- pom.xml
> Release 8.6.8

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
> Release 8.5.14

- pom.xml
> Release 8.6.9-rc1

- assertions/pom.xml
- pom.xml
- qa/testcontainers/pom.xml
Backport of #1496
closes #https://github.com/camunda/zeebe-process-test/issues/1493
> [backport stable/8.4] deps: align camunda model version to 7.22 with camunda/camunda

- assertions/pom.xml
- pom.xml
- qa/testcontainers/pom.xml
Backport of #1496
closes #https://github.com/camunda/zeebe-process-test/issues/1493
> [backport stable/8.7] deps: align camunda model version to 7.22 with camunda/camunda

- api/pom.xml
- assertions/ignored-changes.json
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/AbstractZeebeTestExecutionListener.java
- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/CamundaTestAutoConfiguration.java
- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/configuration/ZeebeTestDefaultConfiguration.java
- spring-test/embedded/pom.xml
- spring-test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
ci: update to zeebe 8.8.0-SNAPSHOT.
> ci: update to zeebe 8.8.0-SNAPSHOT.

- engine/src/main/java/io/camunda/zeebe/process/test/engine/EngineFactory.java
- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDb.java
- pom.xml
- spring-test/common/pom.xml
> Release 8.6.10

- pom.xml
> Release 8.3.21

- pom.xml
> Release 8.5.16

- pom.xml
closes #
Code changes:
Testing:
Documentation:
> Release 8.6.12 rc1

- assertions/src/main/resources/log4j2.xml
- engine/src/main/resources/log4j2.xml
- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/configuration/ZeebeTestDefaultConfiguration.java
- spring-test/testcontainer/pom.xml
- Ensures we log during tests
- Ensures we log all camunda logs at debug level
- Provides a meter registry bean if missing
https://camunda.slack.com/archives/C013MEVQ4M9/p1742786448401559
Code changes:
Testing:
Documentation:
> Fix snapshot build

- spring-test/common/pom.xml
This was flagged by the enforce plugin as a used undeclared dependency.
introduced by #1558 
Code changes:
Testing:
Documentation:
> Declare used dependency micrometer-core

- engine/src/main/java/io/camunda/zeebe/process/test/engine/NoResultsSearchClientsProxy.java
This method was added and without it the compilation of ZPT is broken.
relates to #1562 
Code changes:
Testing:
Documentation:
> Add missing search clients proxy implementation

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
> Release 8.7.0

- spring-test/testcontainer/pom.xml
Backport of #1572 to `release-8.8.0-alpha3`.
relates to
> [Backport release-8.8.0-alpha3] Fix the snapshot build

- pom.xml
> Release 8.3.22

- pom.xml
> Release 8.4.18

- pom.xml
> Release 8.5.17

- assertions/pom.xml
- pom.xml
- qa/testcontainers/pom.xml
Backport of #1496
closes #https://github.com/camunda/zeebe-process-test/issues/1493
> [forwardport main] deps: align camunda model version to 7.22 with camunda/camunda

- spring-test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java
The test setup was relying on the presence of an implicit bean representing the test, being `io.camunda.zeebe.spring.client.jobhandling.JobHandlerTest.ORIGINAL`. Which is not present in the `applicationContext` used now to process worker annotations The fix moves all worker setups into dedicated configuration classes to resolve this.
The cause for it breaking now is a change to SDK but this is nothing relevant for the actual use of the SDK in production code, where workers would always be part of the explicit spring configuration.
See https://camunda.slack.com/archives/C06UWQNCU7M/p1745920644082269
> test: fix test relying availability of implicit test bean

- spring-test/embedded/src/test/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerTest.java
Backport of #1603 to `main`.
relates to
> [Backport main] test: fix test relying availability of implicit test bean

- pom.xml
> Release 8.7.1

- pom.xml
> Release 8.6.14

- spring-test/testcontainer/src/test/java/io/camunda/zeebe/spring/client/jobhandling/SmokeTest.java
Backport of #1607 to `release-8.8.0-alpha4`.
relates to
> [Backport release-8.8.0-alpha4] test: fix smoketest relying on implicit test bean

- pom.xml
> Release 8.6.15-rc1

- pom.xml
> Release 8.4.19

- pom.xml
> Release 8.5.18

- pom.xml
> Release 8.6.15

- pom.xml
- spring-test/common/pom.xml
Backport of https://github.com/camunda/zeebe-process-test/pull/1660#issuecomment-2876340526
> [backport stable/8.7] Manage checker-qual version in parent

- .github/workflows/build-test.yml
- .github/workflows/snapshot-test.yml
- spring-test/testcontainer/pom.xml
Backport of #1617 to `stable/8.6`.
relates to #1389
> [Backport stable/8.6] ci: run spring testcontainers test in tc job

- pom.xml
- spring-test/common/src/main/java/io/camunda/zeebe/spring/test/configuration/ZeebeTestDefaultConfiguration.java
> Release 8.7.3-rc1

- pom.xml
> Release 8.7.3

- .github/workflows/deploy-artifact.yml
Backport of #1691 to `stable/8.6`.
relates to camunda/camunda#31509 #1686
> [Backport stable/8.6] ci: add Slack notification when release is done

- .github/workflows/deploy-artifact.yml
Backport of #1691 to `stable/8.7`.
relates to camunda/camunda#31509 #1686
> [Backport stable/8.7] ci: add Slack notification when release is done

- pom.xml
Downgrade to fix my mistake of bumping too early, since we want to allow the release process to do that now.
> refactor: downgrade for release process

- pom.xml
Downgrades Zeebe to revert my mistake of bumping it too early, as the release process now does that.
> refactor: downgrade

- pom.xml
> Release 8.6.16

- pom.xml
> Release 8.7.4

- pom.xml
> Release 8.6.17

- pom.xml
> Release 8.4.20

- pom.xml
> Release 8.5.19

- pom.xml
> Release 8.6.18

- pom.xml
> Release 8.7.5

- pom.xml
> Release 8.6.19

- pom.xml
Required for publishing to Maven Central as per https://github.com/camunda-community-hub/community/blob/main/maintainers-reviewers/RELEASE.MD#migration-to-sonatype-central-portal--how-to
closes #
Code changes:
Testing:
Documentation:
> deps: Upgrade release parent pom to v2

- engine/src/main/java/io/camunda/zeebe/process/test/engine/db/InMemoryDbColumnFamily.java
Backport of #1758 to `stable/8.4`.
relates to
> [Backport stable/8.4] fix: implement new ColumnFamily method

- pom.xml
> Release 8.5.20

- pom.xml
> Release 8.4.21

- .github/workflows/deploy-artifact.yml
Backport of #1778 to `stable/8.5`.
relates to
> [Backport stable/8.5] ci: Update deploy-artifact.yml

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
> Release 8.6.22

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
> Release 8.6.23

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- filters/src/test/java/io/camunda/zeebe/process/test/filters/logger/RecordStreamLoggerTest.java
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
> Release 8.5.21

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
> Release 8.6.25

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
> Release 8.6.26

- api/pom.xml
- assertions/pom.xml
- engine-agent/pom.xml
- engine-protocol/pom.xml
- engine/pom.xml
- examples/pom.xml
- extension-testcontainer/pom.xml
- extension/pom.xml
- filters/pom.xml
- pom.xml
- qa/abstracts/pom.xml
- qa/embedded/pom.xml
- qa/pom.xml
- qa/testcontainers/pom.xml
- spring-test/common/pom.xml
- spring-test/embedded/pom.xml
- spring-test/pom.xml
- spring-test/testcontainer/pom.xml
Merge the release branch with stable base branch.
> Release 8.6.28
